{{
  config({    
    "materialized": "table",
    "alias": "sh_DIM_PARTY_SK",
    "database": "qa_team",
    "schema": "qa_orchestration"
  })
}}

WITH RTR_New_Existing_SK_JOIN_EXPR_191 AS (

  SELECT *
  
  FROM {{ ref('30_MDL_Party_mp_cnf_mdl_Party_and_Address_and_SK__RTR_New_Existing_SK_JOIN_EXPR_191')}}

),

RTR_New_Existing_SK_out1 AS (

  SELECT * 
  
  FROM RTR_New_Existing_SK_JOIN_EXPR_191 AS in0
  
  WHERE (NewLookupRow_SK = 2)

),

RTR_New_Existing_SK_out0 AS (

  SELECT * 
  
  FROM RTR_New_Existing_SK_JOIN_EXPR_191 AS in0
  
  WHERE (NewLookupRow_SK = 1)

),

RTR_New_Existing_SK_EXPR_Existing_SK AS (

  SELECT 
    REC_STRT_DATE AS REC_STRT_DATE3,
    REC_END_DATE_CLOSED AS REC_END_DATE_CLOSED3,
    REC_END_DATE_HIGH AS REC_END_DATE_HIGH3,
    CTL_REC_CRTN_DATE AS CTL_REC_CRTN_DATE3,
    CTL_JOB_ID AS CTL_JOB_ID3,
    NewLookupRow_SK AS NewLookupRow_SK3,
    GEO_SEGMENT_CODE AS GEO_SEGMENT_CODE3,
    PARTY_NUM AS PARTY_NUM3,
    INTNL_REF_NUM AS INTL_REF_NUM2,
    PARTY_ID_TYPE AS PARTY_ID_TYPE3,
    INTN_REF_ID_TYPE AS INTL_REF_ID_TYPE2,
    PERS_CMPY_FLG AS PERS_CMPY_FLG2,
    PARTY_ID AS PARTY_ID2,
    PARTY_TYPE_CODE AS PARTY_TYPE_CODE3,
    FIRST_NAME AS FIRST_NAME3,
    LAST_NAME AS LAST_NAME3,
    EMAIL_ADDR AS EMAIL_ADDR3,
    TITLE AS TITLE3,
    JOB_TITLE AS JOB_TITLE3,
    OTHER_NAME AS OTHER_NAME3,
    GENDER_FLG AS GENDER_FLG3,
    DOB AS DOB3,
    ABN_LICENCE_NUM AS ABN_LICENCE_NUM3,
    BUSN_PHONE_NUM AS BUSN_PHONE_NUM3,
    PRIVATE_PHONE_NUM AS PRIVATE_PHONE_NUM3,
    FAX_NUM AS FAX_NUM3,
    MOBILE_PHONE_NUM AS MOBILE_PHONE_NUM3,
    WEB_SITE AS WEB_SITE3,
    OUT_VALID_ADDRESS_FLAG AS OUT_VALID_ADDRESS_FLAG3,
    LCTN AS LCTN3,
    DELIVERY_POINT AS DELIVERY_POINT3,
    STREET_NO AS STREET_NO3,
    STREET_NAME AS STREET_NAME3,
    SUBURB AS SUBURB3,
    PCODE AS PCODE3,
    STATE AS STATE3,
    DELIVERY_CODE AS DELIVERY_CODE3,
    GEO_CODE AS GEO_CODE3,
    ADDR_ROLE_CODE AS ADDR_ROLE_CODE3,
    CTL_BATCH_ID AS CTL_BATCH_ID3,
    CTL_SRC_ROW_ID AS CTL_SRC_ROW_ID3,
    CTL_SRC_SYS_SET_NAME AS CTL_SRC_SYS_SET_NAME3,
    CTL_EXTRACT_ID AS CTL_EXTRACT_ID3,
    TAX_FILE_NUM AS TAX_FILE_NUM3,
    IS_PREF_PARTY_DATA AS IS_PREF_PARTY_DATA3,
    ANZSIC_CODE AS ANZSIC_CODE3,
    ACN AS ACN3,
    LOCATION_CODE AS LOCATION_CODE3,
    GEO_SOURCE AS GEO_SOURCE3
  
  FROM RTR_New_Existing_SK_out1 AS in0

),

UNI_Ins_Upd_SK_EXPR_Existing_SK AS (

  SELECT 
    CAST(NULL AS INTEGER) AS NewLookupRow_SK,
    CAST(NULL AS string) AS GEO_SEGMENT_CODE,
    CAST(NULL AS string) AS PARTY_NUM,
    INTL_REF_NUM2 AS INTL_REF_NUM,
    CAST(NULL AS string) AS PARTY_ID_TYPE,
    INTL_REF_ID_TYPE2 AS INTL_REF_ID_TYPE,
    CAST(NULL AS string) AS PARTY_TYPE_CODE,
    PERS_CMPY_FLG2 AS PERS_CMPY_FLG,
    CAST(NULL AS string) AS CTL_SRC_SYS_SET_NAME,
    CAST(NULL AS string) AS REC_START_DATE,
    CAST(NULL AS string) AS CTL_REC_CRTN_DATE,
    CAST(NULL AS INTEGER) AS CTL_JOB_ID,
    CAST(NULL AS INTEGER) AS CTL_BATCH_ID,
    CAST(NULL AS INTEGER) AS CTL_SRC_ROW_ID,
    CAST(NULL AS INTEGER) AS CTL_EXTRACT_ID,
    PARTY_ID2 AS PARTY_ID
  
  FROM RTR_New_Existing_SK_EXPR_Existing_SK AS in0

),

RTR_New_Existing_SK_EXPR_New_SK AS (

  SELECT 
    REC_STRT_DATE AS REC_START_DATE2,
    REC_END_DATE_CLOSED AS REC_END_DATE_CLOSED1,
    REC_END_DATE_HIGH AS REC_END_DATE_HIGH1,
    CTL_REC_CRTN_DATE AS CTL_REC_CRTN_DATE1,
    CTL_JOB_ID AS CTL_JOB_ID1,
    NewLookupRow_SK AS NewLookupRow_SK2,
    GEO_SEGMENT_CODE AS GEO_SEGMENT_CODE1,
    PARTY_NUM AS PARTY_NUM1,
    INTNL_REF_NUM AS INTL_REF_NUM1,
    PARTY_ID_TYPE AS PARTY_ID_TYPE1,
    INTN_REF_ID_TYPE AS INTL_REF_ID_TYPE1,
    PERS_CMPY_FLG AS PERS_CMPY_FLG1,
    PARTY_ID AS PARTY_ID1,
    PARTY_TYPE_CODE AS PARTY_TYPE_CODE1,
    FIRST_NAME AS FIRST_NAME1,
    LAST_NAME AS LAST_NAME1,
    EMAIL_ADDR AS EMAIL_ADDR1,
    TITLE AS TITLE1,
    JOB_TITLE AS JOB_TITLE1,
    OTHER_NAME AS OTHER_NAME1,
    GENDER_FLG AS GENDER_FLG1,
    DOB AS DOB1,
    ABN_LICENCE_NUM AS ABN_LICENCE_NUM1,
    BUSN_PHONE_NUM AS BUSN_PHONE_NUM1,
    PRIVATE_PHONE_NUM AS PRIVATE_PHONE_NUM1,
    FAX_NUM AS FAX_NUM1,
    MOBILE_PHONE_NUM AS MOBILE_PHONE_NUM1,
    WEB_SITE AS WEB_SITE1,
    OUT_VALID_ADDRESS_FLAG AS OUT_VALID_ADDRESS_FLAG1,
    LCTN AS LCTN1,
    DELIVERY_POINT AS DELIVERY_POINT1,
    STREET_NO AS STREET_NO1,
    STREET_NAME AS STREET_NAME1,
    SUBURB AS SUBURB1,
    PCODE AS PCODE1,
    STATE AS STATE1,
    DELIVERY_CODE AS DELIVERY_CODE1,
    GEO_CODE AS GEO_CODE1,
    ADDR_ROLE_CODE AS ADDR_ROLE_CODE1,
    CTL_BATCH_ID AS CTL_BATCH_ID1,
    CTL_SRC_ROW_ID AS CTL_SRC_ROW_ID1,
    CTL_SRC_SYS_SET_NAME AS CTL_SRC_SYS_SET_NAME1,
    CTL_EXTRACT_ID AS CTL_EXTRACT_ID1,
    TAX_FILE_NUM AS TAX_FILE_NUM1,
    IS_PREF_PARTY_DATA AS IS_PREF_PARTY_DATA1,
    ANZSIC_CODE AS ANZSIC_CODE1,
    ACN AS ACN1,
    LOCATION_CODE AS LOCATION_CODE1,
    GEO_SOURCE AS GEO_SOURCE1
  
  FROM RTR_New_Existing_SK_out0 AS in0

),

UNI_Ins_Upd_SK_EXPR_New_SK AS (

  SELECT 
    NewLookupRow_SK2 AS NewLookupRow_SK,
    GEO_SEGMENT_CODE1 AS GEO_SEGMENT_CODE,
    PARTY_NUM1 AS PARTY_NUM,
    INTL_REF_NUM1 AS INTL_REF_NUM,
    PARTY_ID_TYPE1 AS PARTY_ID_TYPE,
    INTL_REF_ID_TYPE1 AS INTL_REF_ID_TYPE,
    PARTY_TYPE_CODE1 AS PARTY_TYPE_CODE,
    PERS_CMPY_FLG1 AS PERS_CMPY_FLG,
    CTL_SRC_SYS_SET_NAME1 AS CTL_SRC_SYS_SET_NAME,
    REC_START_DATE2 AS REC_START_DATE,
    CTL_REC_CRTN_DATE1 AS CTL_REC_CRTN_DATE,
    CTL_JOB_ID1 AS CTL_JOB_ID,
    CTL_BATCH_ID1 AS CTL_BATCH_ID,
    CTL_SRC_ROW_ID1 AS CTL_SRC_ROW_ID,
    CTL_EXTRACT_ID1 AS CTL_EXTRACT_ID,
    PARTY_ID1 AS PARTY_ID
  
  FROM RTR_New_Existing_SK_EXPR_New_SK AS in0

),

UNI_Ins_Upd_SK AS (

  {{
    prophecy_basics.UnionByName(
      ['UNI_Ins_Upd_SK_EXPR_New_SK', 'UNI_Ins_Upd_SK_EXPR_Existing_SK'], 
      [
        '[{"name": "NewLookupRow_SK", "dataType": "Integer"}, {"name": "GEO_SEGMENT_CODE", "dataType": "String"}, {"name": "PARTY_NUM", "dataType": "String"}, {"name": "INTL_REF_NUM", "dataType": "String"}, {"name": "PARTY_ID_TYPE", "dataType": "String"}, {"name": "INTL_REF_ID_TYPE", "dataType": "String"}, {"name": "PARTY_TYPE_CODE", "dataType": "String"}, {"name": "PERS_CMPY_FLG", "dataType": "String"}, {"name": "CTL_SRC_SYS_SET_NAME", "dataType": "String"}, {"name": "REC_START_DATE", "dataType": "Timestamp"}, {"name": "CTL_REC_CRTN_DATE", "dataType": "Timestamp"}, {"name": "CTL_JOB_ID", "dataType": "Integer"}, {"name": "CTL_BATCH_ID", "dataType": "Integer"}, {"name": "CTL_SRC_ROW_ID", "dataType": "Integer"}, {"name": "CTL_EXTRACT_ID", "dataType": "Integer"}, {"name": "PARTY_ID", "dataType": "Integer"}]', 
        '[{"name": "NewLookupRow_SK", "dataType": "Integer"}, {"name": "GEO_SEGMENT_CODE", "dataType": "String"}, {"name": "PARTY_NUM", "dataType": "String"}, {"name": "INTL_REF_NUM", "dataType": "String"}, {"name": "PARTY_ID_TYPE", "dataType": "String"}, {"name": "INTL_REF_ID_TYPE", "dataType": "String"}, {"name": "PARTY_TYPE_CODE", "dataType": "String"}, {"name": "PERS_CMPY_FLG", "dataType": "String"}, {"name": "CTL_SRC_SYS_SET_NAME", "dataType": "String"}, {"name": "REC_START_DATE", "dataType": "String"}, {"name": "CTL_REC_CRTN_DATE", "dataType": "String"}, {"name": "CTL_JOB_ID", "dataType": "Integer"}, {"name": "CTL_BATCH_ID", "dataType": "Integer"}, {"name": "CTL_SRC_ROW_ID", "dataType": "Integer"}, {"name": "CTL_EXTRACT_ID", "dataType": "Integer"}, {"name": "PARTY_ID", "dataType": "Integer"}]'
      ], 
      'allowMissingColumns'
    )
  }}

)

SELECT *

FROM UNI_Ins_Upd_SK
