{{
  config({    
    "materialized": "table",
    "alias": "sh_DIM_PARTY",
    "database": "zurich_pov",
    "schema": "zurich"
  })
}}

WITH RTR_New_Existing_SK_EXPR_All AS (

  SELECT *
  
  FROM {{ ref('30_MDL_Party_mp_cnf_mdl_Party_and_Address_and_SK__RTR_New_Existing_SK_EXPR_All')}}

),

RTR_New_Existing_SK_EXPR_All_EXPR_205 AS (

  SELECT 
    CTL_BATCH_ID4 AS CTL_BATCH_ID,
    CTL_SRC_ROW_ID4 AS CTL_SRC_ROW_ID,
    CTL_SRC_SYS_SET_NAME4 AS CTL_SRC_SYS_SET_NAME,
    CTL_EXTRACT_ID4 AS CTL_EXTRACT_ID,
    ACN4 AS ACN,
    REC_END_DATE_HIGH4 AS REC_END_DATE_HIGH,
    CTL_REC_CRTN_DATE4 AS CTL_REC_CRTN_DATE,
    CTL_JOB_ID4 AS CTL_JOB_ID,
    INTNL_REF_NUM4 AS INTNL_REF_NUM,
    PARTY_ID_TYPE4 AS PARTY_ID_TYPE,
    INTN_REF_ID_TYPE4 AS INTN_REF_ID_TYPE,
    PERS_CMPY_FLG4 AS PERS_CMPY_FLG,
    EMAIL_ADDR4 AS EMAIL_ADDR,
    TITLE4 AS TITLE,
    JOB_TITLE4 AS JOB_TITLE,
    OTHER_NAME4 AS OTHER_NAME,
    PRIVATE_PHONE_NUM4 AS PRIVATE_PHONE_NUM,
    FAX_NUM4 AS FAX_NUM,
    MOBILE_PHONE_NUM4 AS MOBILE_PHONE_NUM,
    WEB_SITE4 AS WEB_SITE,
    TAX_FILE_NUM4 AS TAX_FILE_NUM,
    IS_PREF_PARTY_DATA4 AS IS_PREF_PARTY_DATA,
    REC_END_DATE_CLOSED4 AS REC_END_DATE_CLOSED,
    ANZSIC_CODE4 AS ANZSIC_CODE,
    REC_STRT_DATE4 AS REC_STRT_DATE,
    NewLookupRow_SK4 AS NewLookupRow_SK,
    GEO_SEGMENT_CODE4 AS GEO_SEGMENT_CODE,
    PARTY_NUM4 AS PARTY_NUM,
    PARTY_ID4 AS PARTY_ID,
    PARTY_TYPE_CODE4 AS PARTY_TYPE_CODE,
    FIRST_NAME4 AS FIRST_NAME,
    LAST_NAME4 AS LAST_NAME,
    GENDER_FLG4 AS GENDER_FLG,
    DOB4 AS DOB,
    ABN_LICENCE_NUM4 AS ABN_LICENCE_NUM,
    BUSN_PHONE_NUM4 AS BUSN_PHONE_NUM,
    OUT_VALID_ADDRESS_FLAG4 AS OUT_VALID_ADDRESS_FLAG4,
    LCTN4 AS LCTN4,
    DELIVERY_POINT4 AS DELIVERY_POINT4,
    STREET_NO4 AS STREET_NO4,
    STREET_NAME4 AS STREET_NAME4,
    SUBURB4 AS SUBURB4,
    PCODE4 AS PCODE4,
    STATE4 AS STATE4,
    DELIVERY_CODE4 AS DELIVERY_CODE4,
    GEO_CODE4 AS GEO_CODE4,
    ADDR_ROLE_CODE4 AS ADDR_ROLE_CODE4,
    LOCATION_CODE4 AS LOCATION_CODE4,
    GEO_SOURCE4 AS GEO_SOURCE4
  
  FROM RTR_New_Existing_SK_EXPR_All AS in0

),

FIL_Remove_Pref_Party_Data AS (

  SELECT * 
  
  FROM RTR_New_Existing_SK_EXPR_All_EXPR_205 AS in0
  
  WHERE CAST((IS_PREF_PARTY_DATA = 0) AS BOOLEAN)

),

FIL_Remove_Pref_Party_Data_GENERATE_SK_0 AS (

  SELECT 
    (monotonically_increasing_id()) AS prophecy_sk,
    *
  
  FROM FIL_Remove_Pref_Party_Data AS in0

),

`30_MDL_Partymp_cnf_mdl_Party_and_Address_and_SK_SOURCE_LKP_Dyn_Dim_Party` AS (

  SELECT *
  
  FROM {{
    prophecy_tmp_source(
      '30_MDL_Party_mp_cnf_mdl_Party_and_Address_and_SK', 
      '30_MDL_Partymp_cnf_mdl_Party_and_Address_and_SK_SOURCE_LKP_Dyn_Dim_Party'
    )
  }}

),

FIL_Remove_Pref_Party_Data_GENERATE_SK_EXPR_203 AS (

  SELECT 
    EMAIL_ADDR AS IN_EMAIL_ADDR,
    TITLE AS IN_TITLE,
    JOB_TITLE AS IN_JOB_TITLE,
    OTHER_NAME AS IN_OTHER_NAME,
    PRIVATE_PHONE_NUM AS IN_PRIVATE_PHONE_NUM,
    FAX_NUM AS IN_FAX_NUM,
    MOBILE_PHONE_NUM AS IN_MOBILE_PHONE_NUM,
    WEB_SITE AS IN_WEB_SITE,
    PARTY_ID AS IN_PARTY_ID,
    FIRST_NAME AS IN_FIRST_NAME,
    LAST_NAME AS IN_LAST_NAME,
    GENDER_FLG AS IN_GENDER_FLG,
    DOB AS IN_DOB,
    ABN_LICENCE_NUM AS IN_ABN_LICENCE_NUM,
    BUSN_PHONE_NUM AS IN_BUSN_PHONE_NUM,
    TAX_FILE_NUM AS IN_TAX_FILE_NUM,
    REC_STRT_DATE AS IN_REC_STRT_DATE,
    ANZSIC_CODE AS IN_ANZSIC_CODE,
    ACN AS IN_ACN,
    prophecy_sk AS prophecy_sk,
    PARTY_ID_TYPE AS PARTY_ID_TYPE,
    INTN_REF_ID_TYPE AS INTN_REF_ID_TYPE,
    PARTY_TYPE_CODE AS PARTY_TYPE_CODE,
    PERS_CMPY_FLG AS PERS_CMPY_FLG,
    REC_END_DATE_CLOSED AS REC_END_DATE_CLOSED,
    CTL_REC_CRTN_DATE AS CTL_REC_CRTN_DATE,
    CTL_JOB_ID AS CTL_JOB_ID,
    NewLookupRow_SK AS NewLookupRow_SK,
    GEO_SEGMENT_CODE AS GEO_SEGMENT_CODE,
    PARTY_NUM AS PARTY_NUM,
    INTNL_REF_NUM AS INTNL_REF_NUM,
    CTL_SRC_SYS_SET_NAME AS CTL_SRC_SYS_SET_NAME,
    CTL_BATCH_ID AS CTL_BATCH_ID,
    CTL_SRC_ROW_ID AS CTL_SRC_ROW_ID,
    CTL_EXTRACT_ID AS CTL_EXTRACT_ID,
    REC_END_DATE_HIGH AS REC_END_DATE_HIGH
  
  FROM FIL_Remove_Pref_Party_Data_GENERATE_SK_0 AS in0

),

LKP_Dyn_Dim_Party_JOIN AS (

  SELECT 
    in0.EMAIL_ADDR AS EMAIL_ADDR,
    in1.IN_EMAIL_ADDR AS IN_EMAIL_ADDR,
    in0.FIRST_NAME AS FIRST_NAME,
    in1.IN_REC_STRT_DATE AS IN_REC_STRT_DATE,
    in0.TAX_FILE_NUM AS TAX_FILE_NUM,
    in1.IN_MOBILE_PHONE_NUM AS IN_MOBILE_PHONE_NUM,
    in0.NewLookupRow AS NewLookupRow,
    in0.WEB_SITE AS WEB_SITE,
    in0.DOB AS DOB,
    in0.REC_STRT_DATE AS REC_STRT_DATE,
    in0.JOB_TITLE AS JOB_TITLE,
    in1.IN_JOB_TITLE AS IN_JOB_TITLE,
    in1.IN_GENDER_FLG AS IN_GENDER_FLG,
    in1.IN_ANZSIC_CODE AS IN_ANZSIC_CODE,
    in1.IN_OTHER_NAME AS IN_OTHER_NAME,
    in1.IN_ACN AS IN_ACN,
    in1.IN_PRIVATE_PHONE_NUM AS IN_PRIVATE_PHONE_NUM,
    in0.GENDER_FLG AS GENDER_FLG,
    in1.IN_LAST_NAME AS IN_LAST_NAME,
    in1.IN_TAX_FILE_NUM AS IN_TAX_FILE_NUM,
    in1.IN_WEB_SITE AS IN_WEB_SITE,
    in1.IN_FIRST_NAME AS IN_FIRST_NAME,
    in1.IN_DOB AS IN_DOB,
    in0.MOBILE_PHONE_NUM AS MOBILE_PHONE_NUM,
    in0.ACN AS ACN,
    in0.LAST_NAME AS LAST_NAME,
    in1.IN_ABN_LICENCE_NUM AS IN_ABN_LICENCE_NUM,
    in1.prophecy_sk AS prophecy_sk,
    in0.OTHER_NAME AS OTHER_NAME,
    in0.FAX_NUM AS FAX_NUM,
    in0.PARTY_ID AS PARTY_ID,
    in0.ABN_LICENCE_NUM AS ABN_LICENCE_NUM,
    in1.IN_PARTY_ID AS IN_PARTY_ID,
    in1.IN_FAX_NUM AS IN_FAX_NUM,
    in0.TITLE AS TITLE,
    in0.ANZSIC_CODE AS ANZSIC_CODE,
    in1.IN_BUSN_PHONE_NUM AS IN_BUSN_PHONE_NUM,
    in1.IN_TITLE AS IN_TITLE,
    in0.PRIVATE_PHONE_NUM AS PRIVATE_PHONE_NUM,
    in0.BUSN_PHONE_NUM AS BUSN_PHONE_NUM
  
  FROM `30_MDL_Partymp_cnf_mdl_Party_and_Address_and_SK_SOURCE_LKP_Dyn_Dim_Party` AS in0
  INNER JOIN FIL_Remove_Pref_Party_Data_GENERATE_SK_EXPR_203 AS in1
     ON (in0.PARTY_ID = in1.IN_PARTY_ID)

),

LKP_Dyn_Dim_Party_JOIN_EXPR_199 AS (

  SELECT 
    TITLE AS LKP_TITLE,
    IN_EMAIL_ADDR AS IN_EMAIL_ADDR,
    IN_OTHER_NAME AS IN_OTHER_NAME,
    IN_GENDER_FLG AS IN_GENDER_FLG,
    IN_DOB AS IN_DOB,
    IN_WEB_SITE AS IN_WEB_SITE,
    IN_ABN_LICENCE_NUM AS IN_ABN_LICENCE_NUM,
    IN_TITLE AS IN_TITLE,
    IN_JOB_TITLE AS IN_JOB_TITLE,
    REC_STRT_DATE AS lk_REC_STRT_DATE,
    IN_ANZSIC_CODE AS ANZSIC_CODE,
    IN_ACN AS ACN,
    ANZSIC_CODE AS LKP_ANZSIC_CODE,
    DOB AS LKP_DOB,
    ABN_LICENCE_NUM AS LKP_ABN_LICENCE_NUM,
    BUSN_PHONE_NUM AS LKP_BUSN_PHONE_NUM,
    PRIVATE_PHONE_NUM AS LKP_PRIVATE_PHONE_NUM,
    FAX_NUM AS LKP_FAX_NUM,
    MOBILE_PHONE_NUM AS LKP_MOBILE_PHONE_NUM,
    WEB_SITE AS LKP_WEB_SITE,
    TAX_FILE_NUM AS LKP_TAX_FILE_NUM,
    IN_PARTY_ID AS IN_PARTY_ID,
    IN_FIRST_NAME AS IN_FIRST_NAME,
    IN_LAST_NAME AS IN_LAST_NAME,
    IN_BUSN_PHONE_NUM AS IN_BUSN_PHONE_NUM,
    IN_PRIVATE_PHONE_NUM AS IN_PRIVATE_PHONE_NUM,
    IN_MOBILE_PHONE_NUM AS IN_MOBILE_PHONE_NUM,
    IN_FAX_NUM AS IN_FAX_NUM,
    IN_TAX_FILE_NUM AS IN_TAX_FILE_NUM,
    NewLookupRow AS NewLookupRow,
    PARTY_ID AS LKP_PARTY_ID,
    IN_REC_STRT_DATE AS IN_REC_STRT_DATE,
    ACN AS LKP_ACN,
    JOB_TITLE AS LKP_JOB_TITLE,
    OTHER_NAME AS LKP_OTHER_NAME,
    GENDER_FLG AS LKP_GENDER_FLG,
    FIRST_NAME AS LKP_FIRST_NAME,
    LAST_NAME AS LKP_LAST_NAME,
    EMAIL_ADDR AS LKP_EMAIL_ADDR,
    prophecy_sk AS prophecy_sk
  
  FROM LKP_Dyn_Dim_Party_JOIN AS in0

),

RTR_New_SK_New_Existing_party_JOIN AS (

  SELECT 
    in0.EMAIL_ADDR AS EMAIL_ADDR,
    in0.PARTY_ID_TYPE AS PARTY_ID_TYPE,
    in1.IN_EMAIL_ADDR AS IN_EMAIL_ADDR,
    in0.FIRST_NAME AS FIRST_NAME,
    in0.NewLookupRow_SK AS NewLookupRow_SK,
    in0.TAX_FILE_NUM AS TAX_FILE_NUM,
    in1.IN_MOBILE_PHONE_NUM AS IN_MOBILE_PHONE_NUM,
    in1.NewLookupRow AS NewLookupRow,
    in0.WEB_SITE AS WEB_SITE,
    in0.CTL_BATCH_ID AS CTL_BATCH_ID,
    in0.CTL_SRC_SYS_SET_NAME AS CTL_SRC_SYS_SET_NAME,
    in0.DOB AS DOB,
    in0.REC_STRT_DATE AS REC_STRT_DATE,
    in0.JOB_TITLE AS JOB_TITLE,
    in1.IN_JOB_TITLE AS IN_JOB_TITLE,
    in1.IN_GENDER_FLG AS IN_GENDER_FLG,
    in1.IN_OTHER_NAME AS IN_OTHER_NAME,
    in0.PARTY_TYPE_CODE AS PARTY_TYPE_CODE,
    in1.IN_PRIVATE_PHONE_NUM AS IN_PRIVATE_PHONE_NUM,
    in1.lk_REC_STRT_DATE AS lk_REC_STRT_DATE,
    in0.GENDER_FLG AS GENDER_FLG,
    in0.CTL_REC_CRTN_DATE AS CTL_REC_CRTN_DATE,
    in0.CTL_EXTRACT_ID AS CTL_EXTRACT_ID,
    in0.REC_END_DATE_HIGH AS REC_END_DATE_HIGH,
    in1.IN_LAST_NAME AS IN_LAST_NAME,
    in1.IN_TAX_FILE_NUM AS IN_TAX_FILE_NUM,
    in1.IN_WEB_SITE AS IN_WEB_SITE,
    in1.IN_FIRST_NAME AS IN_FIRST_NAME,
    in1.IN_DOB AS IN_DOB,
    in0.MOBILE_PHONE_NUM AS MOBILE_PHONE_NUM,
    in0.ACN AS ACN,
    in0.REC_END_DATE_CLOSED AS REC_END_DATE_CLOSED,
    in0.PARTY_NUM AS PARTY_NUM,
    in0.LAST_NAME AS LAST_NAME,
    in1.IN_ABN_LICENCE_NUM AS IN_ABN_LICENCE_NUM,
    in0.prophecy_sk AS prophecy_sk,
    in0.OTHER_NAME AS OTHER_NAME,
    in0.INTN_REF_ID_TYPE AS INTN_REF_ID_TYPE,
    in0.FAX_NUM AS FAX_NUM,
    in0.PARTY_ID AS PARTY_ID,
    in0.ABN_LICENCE_NUM AS ABN_LICENCE_NUM,
    in0.INTNL_REF_NUM AS INTNL_REF_NUM,
    in1.IN_PARTY_ID AS IN_PARTY_ID,
    in1.IN_FAX_NUM AS IN_FAX_NUM,
    in0.TITLE AS TITLE,
    in0.PERS_CMPY_FLG AS PERS_CMPY_FLG,
    in0.GEO_SEGMENT_CODE AS GEO_SEGMENT_CODE,
    in0.ANZSIC_CODE AS ANZSIC_CODE,
    in1.IN_BUSN_PHONE_NUM AS IN_BUSN_PHONE_NUM,
    in1.IN_TITLE AS IN_TITLE,
    in0.PRIVATE_PHONE_NUM AS PRIVATE_PHONE_NUM,
    in0.BUSN_PHONE_NUM AS BUSN_PHONE_NUM,
    in0.CTL_JOB_ID AS CTL_JOB_ID,
    in0.CTL_SRC_ROW_ID AS CTL_SRC_ROW_ID
  
  FROM FIL_Remove_Pref_Party_Data_GENERATE_SK_0 AS in0
  INNER JOIN LKP_Dyn_Dim_Party_JOIN_EXPR_199 AS in1
     ON (in0.prophecy_sk = in1.prophecy_sk)

),

RTR_New_SK_New_Existing_party_JOIN_EXPR_193 AS (

  SELECT 
    PARTY_ID_TYPE AS PARTY_ID_TYPE,
    INTN_REF_ID_TYPE AS INTN_REF_ID_TYPE,
    PARTY_TYPE_CODE AS PARTY_TYPE_CODE,
    PERS_CMPY_FLG AS PERS_CMPY_FLG,
    REC_STRT_DATE AS REC_STRT_DATE,
    REC_END_DATE_CLOSED AS REC_END_DATE_CLOSED,
    CTL_REC_CRTN_DATE AS CTL_REC_CRTN_DATE,
    CTL_JOB_ID AS CTL_JOB_ID,
    NewLookupRow_SK AS NewLookupRow_SK,
    GEO_SEGMENT_CODE AS GEO_SEGMENT_CODE,
    PARTY_NUM AS PARTY_NUM,
    INTNL_REF_NUM AS INTNL_REF_NUM,
    CTL_SRC_SYS_SET_NAME AS CTL_SRC_SYS_SET_NAME,
    CTL_BATCH_ID AS CTL_BATCH_ID,
    CTL_SRC_ROW_ID AS CTL_SRC_ROW_ID,
    CTL_EXTRACT_ID AS CTL_EXTRACT_ID,
    REC_END_DATE_HIGH AS REC_END_DATE_HIGH,
    ANZSIC_CODE AS ANZSIC_CODE,
    EMAIL_ADDR AS EMAIL_ADDR,
    WEB_SITE AS WEB_SITE,
    LAST_NAME AS LAST_NAME,
    TITLE AS TITLE,
    BUSN_PHONE_NUM AS BUSN_PHONE_NUM,
    GENDER_FLG AS GENDER_FLG,
    MOBILE_PHONE_NUM AS MOBILE_PHONE_NUM,
    PRIVATE_PHONE_NUM AS PRIVATE_PHONE_NUM,
    DOB AS DOB,
    FIRST_NAME AS FIRST_NAME,
    PARTY_ID AS PARTY_ID,
    OTHER_NAME AS OTHER_NAME,
    TAX_FILE_NUM AS TAX_FILE_NUM,
    ACN AS ACN,
    FAX_NUM AS FAX_NUM,
    ABN_LICENCE_NUM AS ABN_LICENCE_NUM,
    JOB_TITLE AS JOB_TITLE,
    prophecy_sk AS prophecy_sk,
    NewLookupRow AS NewLookupRow,
    lk_REC_STRT_DATE AS lk_REC_STRT_DATE
  
  FROM RTR_New_SK_New_Existing_party_JOIN AS in0

),

RTR_New_SK_New_Existing_party_out1 AS (

  SELECT * 
  
  FROM RTR_New_SK_New_Existing_party_JOIN_EXPR_193 AS in0
  
  WHERE ((NewLookupRow = 2) AND (REC_STRT_DATE > lk_REC_STRT_DATE))

),

RTR_New_SK_New_Existing_party_out0 AS (

  SELECT * 
  
  FROM RTR_New_SK_New_Existing_party_JOIN_EXPR_193 AS in0
  
  WHERE ((NewLookupRow = 1) AND (lk_REC_STRT_DATE IS NULL))

),

RTR_New_SK_New_Existing_party_EXPR_Existing_Party AS (

  SELECT 
    NewLookupRow_SK AS NewLookupRow_SK3,
    GEO_SEGMENT_CODE AS GEO_SEGMENT_CODE3,
    PARTY_NUM AS PARTY_NUM3,
    INTNL_REF_NUM AS INTNL_REF_NUM3,
    PARTY_ID_TYPE AS PARTY_ID_TYPE3,
    INTN_REF_ID_TYPE AS INTN_REF_ID_TYPE3,
    PARTY_TYPE_CODE AS PARTY_TYPE_CODE3,
    PERS_CMPY_FLG AS PERS_CMPY_FLG3,
    CTL_SRC_SYS_SET_NAME AS CTL_SRC_SYS_SET_NAME3,
    REC_STRT_DATE AS REC_STRT_DATE3,
    CTL_REC_CRTN_DATE AS CTL_REC_CRTN_DATE3,
    REC_END_DATE_CLOSED AS REC_END_DATE_CLOSED3,
    REC_END_DATE_HIGH AS REC_END_DATE_HIGH3,
    CTL_JOB_ID AS CTL_JOB_ID3,
    CTL_BATCH_ID AS CTL_BATCH_ID3,
    CTL_SRC_ROW_ID AS CTL_SRC_ROW_ID3,
    CTL_EXTRACT_ID AS CTL_EXTRACT_ID3,
    NewLookupRow AS NewLookupRow3,
    PARTY_ID AS PARTY_ID3,
    FIRST_NAME AS FIRST_NAME3,
    LAST_NAME AS LAST_NAME3,
    EMAIL_ADDR AS EMAIL_ADDR3,
    TITLE AS TITLE3,
    JOB_TITLE AS JOB_TITLE3,
    OTHER_NAME AS OTHER_NAME3,
    GENDER_FLG AS GENDER_FLG3,
    DOB AS DOB3,
    ABN_LICENCE_NUM AS ABN_LICENCE_NUM3,
    BUSN_PHONE_NUM AS BUSN_PHONE_NUM3,
    PRIVATE_PHONE_NUM AS PRIVATE_PHONE_NUM3,
    FAX_NUM AS FAX_NUM3,
    MOBILE_PHONE_NUM AS MOBILE_PHONE_NUM3,
    WEB_SITE AS WEB_SITE3,
    TAX_FILE_NUM AS TAX_FILE_NUM3,
    lk_REC_STRT_DATE AS lk_REC_STRT_DATE3,
    ANZSIC_CODE AS ANZSIC_CODE3,
    ACN AS ACN3,
    ACN AS ACN2,
    INTNL_REF_NUM AS INTNL_REF_NUM2,
    PARTY_ID_TYPE AS PARTY_ID_TYPE2,
    GEO_SEGMENT_CODE AS GEO_SEGMENT_CODE2,
    PARTY_NUM AS PARTY_NUM2,
    PERS_CMPY_FLG AS PERS_CMPY_FLG2,
    CTL_SRC_SYS_SET_NAME AS CTL_SRC_SYS_SET_NAME2,
    REC_STRT_DATE AS REC_STRT_DATE2,
    CTL_REC_CRTN_DATE AS CTL_REC_CRTN_DATE2,
    REC_END_DATE_HIGH AS REC_END_DATE2,
    CTL_JOB_ID AS CTL_JOB_ID2,
    CTL_BATCH_ID AS CTL_BATCH_ID2,
    CTL_SRC_ROW_ID AS CTL_SRC_ROW_ID2,
    CTL_EXTRACT_ID AS CTL_EXTRACT_ID2,
    TITLE AS TITLE2,
    JOB_TITLE AS JOB_TITLE2,
    OTHER_NAME AS OTHER_NAME2,
    GENDER_FLG AS GENDER_FLG2,
    FAX_NUM AS FAX_NUM2,
    MOBILE_PHONE_NUM AS MOBILE_PHONE_NUM2,
    WEB_SITE AS WEB_SITE2,
    TAX_FILE_NUM AS TAX_FILE_NUM2,
    ANZSIC_CODE AS ANZSIC_CODE2,
    INTN_REF_ID_TYPE AS INTN_REF_ID_TYPE2,
    PARTY_TYPE_CODE AS PARTY_TYPE_CODE2,
    PARTY_ID AS PARTY_ID2,
    FIRST_NAME AS FIRST_NAME2,
    LAST_NAME AS LAST_NAME2,
    EMAIL_ADDR AS EMAIL_ADDR2,
    DOB AS DOB2,
    ABN_LICENCE_NUM AS ABN_LICENCE_NUM2,
    BUSN_PHONE_NUM AS BUSN_PHONE_NUM2,
    PRIVATE_PHONE_NUM AS PRIVATE_PHONE_NUM2,
    REC_END_DATE_CLOSED AS REC_END_DATE1,
    CTL_REC_CRTN_DATE AS CTL_REC_UPDATE_DATE1,
    PARTY_ID AS PARTY_ID1,
    REC_STRT_DATE AS REC_STRT_DATE1
  
  FROM RTR_New_SK_New_Existing_party_out1 AS in0

),

UNI_New_Existing_Party_EXPR_Existing_Insert AS (

  SELECT 
    GEO_SEGMENT_CODE2 AS GEO_SEGMENT_CODE,
    PARTY_NUM2 AS PARTY_NUM,
    INTNL_REF_NUM2 AS INTNL_REF_NUM,
    PARTY_ID_TYPE2 AS PARTY_ID_TYPE,
    INTN_REF_ID_TYPE2 AS INTN_REF_ID_TYPE,
    PARTY_TYPE_CODE2 AS PARTY_TYPE_CODE,
    PERS_CMPY_FLG2 AS PERS_CMPY_FLG,
    CTL_SRC_SYS_SET_NAME2 AS CTL_SRC_SYS_SET_NAME,
    REC_STRT_DATE2 AS REC_STRT_DATE,
    CTL_REC_CRTN_DATE2 AS CTL_REC_CRTN_DATE,
    REC_END_DATE2 AS REC_END_DATE,
    CTL_JOB_ID2 AS CTL_JOB_ID,
    CTL_BATCH_ID2 AS CTL_BATCH_ID,
    CTL_SRC_ROW_ID2 AS CTL_SRC_ROW_ID,
    CTL_EXTRACT_ID2 AS CTL_EXTRACT_ID,
    CAST(NULL AS STRING) AS CTL_REC_UPDATE_DATE,
    PARTY_ID2 AS PARTY_ID,
    FIRST_NAME2 AS FIRST_NAME,
    LAST_NAME2 AS LAST_NAME,
    EMAIL_ADDR2 AS EMAIL_ADDR,
    TITLE2 AS TITLE,
    JOB_TITLE2 AS JOB_TITLE,
    OTHER_NAME2 AS OTHER_NAME,
    GENDER_FLG2 AS GENDER_FLG,
    DOB2 AS DOB,
    ABN_LICENCE_NUM2 AS ABN_LICENCE_NUM,
    BUSN_PHONE_NUM2 AS BUSN_PHONE_NUM,
    PRIVATE_PHONE_NUM2 AS PRIVATE_PHONE_NUM,
    FAX_NUM2 AS FAX_NUM,
    MOBILE_PHONE_NUM2 AS MOBILE_PHONE_NUM,
    WEB_SITE2 AS WEB_SITE,
    TAX_FILE_NUM2 AS TAX_FILE_NUM,
    ANZSIC_CODE2 AS ANZSIC_CODE,
    ACN2 AS ACN
  
  FROM RTR_New_SK_New_Existing_party_EXPR_Existing_Party AS in0

),

RTR_New_SK_New_Existing_party_EXPR_New_Party AS (

  SELECT 
    NewLookupRow_SK AS NewLookupRow_SK1,
    GEO_SEGMENT_CODE AS GEO_SEGMENT_CODE3,
    PARTY_NUM AS PARTY_NUM3,
    INTNL_REF_NUM AS INTNL_REF_NUM3,
    PARTY_ID_TYPE AS PARTY_ID_TYPE3,
    INTN_REF_ID_TYPE AS INTN_REF_ID_TYPE3,
    PARTY_TYPE_CODE AS PARTY_TYPE_CODE3,
    PERS_CMPY_FLG AS PERS_CMPY_FLG3,
    CTL_SRC_SYS_SET_NAME AS CTL_SRC_SYS_SET_NAME3,
    REC_STRT_DATE AS REC_STRT_DATE3,
    CTL_REC_CRTN_DATE AS CTL_REC_CRTN_DATE3,
    REC_END_DATE_CLOSED AS REC_END_DATE_CLOSED1,
    REC_END_DATE_HIGH AS REC_END_DATE3,
    CTL_JOB_ID AS CTL_JOB_ID3,
    CTL_BATCH_ID AS CTL_BATCH_ID3,
    CTL_SRC_ROW_ID AS CTL_SRC_ROW_ID3,
    CTL_EXTRACT_ID AS CTL_EXTRACT_ID3,
    NewLookupRow AS NewLookupRow1,
    PARTY_ID AS PARTY_ID3,
    FIRST_NAME AS FIRST_NAME3,
    LAST_NAME AS LAST_NAME3,
    EMAIL_ADDR AS EMAIL_ADDR3,
    TITLE AS TITLE3,
    JOB_TITLE AS JOB_TITLE3,
    OTHER_NAME AS OTHER_NAME3,
    GENDER_FLG AS GENDER_FLG3,
    DOB AS DOB3,
    ABN_LICENCE_NUM AS ABN_LICENCE_NUM3,
    BUSN_PHONE_NUM AS BUSN_PHONE_NUM3,
    PRIVATE_PHONE_NUM AS PRIVATE_PHONE_NUM3,
    FAX_NUM AS FAX_NUM3,
    MOBILE_PHONE_NUM AS MOBILE_PHONE_NUM3,
    WEB_SITE AS WEB_SITE3,
    TAX_FILE_NUM AS TAX_FILE_NUM3,
    lk_REC_STRT_DATE AS lk_REC_STRT_DATE1,
    ANZSIC_CODE AS ANZSIC_CODE3,
    ACN AS ACN3
  
  FROM RTR_New_SK_New_Existing_party_out0 AS in0

),

UNI_New_Existing_Party_EXPR_New_Insert AS (

  SELECT 
    GEO_SEGMENT_CODE3 AS GEO_SEGMENT_CODE,
    PARTY_NUM3 AS PARTY_NUM,
    INTNL_REF_NUM3 AS INTNL_REF_NUM,
    PARTY_ID_TYPE3 AS PARTY_ID_TYPE,
    INTN_REF_ID_TYPE3 AS INTN_REF_ID_TYPE,
    PARTY_TYPE_CODE3 AS PARTY_TYPE_CODE,
    PERS_CMPY_FLG3 AS PERS_CMPY_FLG,
    CTL_SRC_SYS_SET_NAME3 AS CTL_SRC_SYS_SET_NAME,
    REC_STRT_DATE3 AS REC_STRT_DATE,
    CTL_REC_CRTN_DATE3 AS CTL_REC_CRTN_DATE,
    REC_END_DATE3 AS REC_END_DATE,
    CTL_JOB_ID3 AS CTL_JOB_ID,
    CTL_BATCH_ID3 AS CTL_BATCH_ID,
    CTL_SRC_ROW_ID3 AS CTL_SRC_ROW_ID,
    CTL_EXTRACT_ID3 AS CTL_EXTRACT_ID,
    CAST(NULL AS STRING) AS CTL_REC_UPDATE_DATE,
    PARTY_ID3 AS PARTY_ID,
    FIRST_NAME3 AS FIRST_NAME,
    LAST_NAME3 AS LAST_NAME,
    EMAIL_ADDR3 AS EMAIL_ADDR,
    TITLE3 AS TITLE,
    JOB_TITLE3 AS JOB_TITLE,
    OTHER_NAME3 AS OTHER_NAME,
    GENDER_FLG3 AS GENDER_FLG,
    DOB3 AS DOB,
    ABN_LICENCE_NUM3 AS ABN_LICENCE_NUM,
    BUSN_PHONE_NUM3 AS BUSN_PHONE_NUM,
    PRIVATE_PHONE_NUM3 AS PRIVATE_PHONE_NUM,
    FAX_NUM3 AS FAX_NUM,
    MOBILE_PHONE_NUM3 AS MOBILE_PHONE_NUM,
    WEB_SITE3 AS WEB_SITE,
    TAX_FILE_NUM3 AS TAX_FILE_NUM,
    ANZSIC_CODE3 AS ANZSIC_CODE,
    ACN3 AS ACN
  
  FROM RTR_New_SK_New_Existing_party_EXPR_New_Party AS in0

),

UNI_New_Existing_Party_EXPR_Existing_Update AS (

  SELECT 
    CAST(NULL AS STRING) AS GEO_SEGMENT_CODE,
    CAST(NULL AS STRING) AS PARTY_NUM,
    CAST(NULL AS STRING) AS INTNL_REF_NUM,
    CAST(NULL AS STRING) AS PARTY_ID_TYPE,
    CAST(NULL AS STRING) AS INTN_REF_ID_TYPE,
    CAST(NULL AS STRING) AS PARTY_TYPE_CODE,
    CAST(NULL AS STRING) AS PERS_CMPY_FLG,
    CAST(NULL AS STRING) AS CTL_SRC_SYS_SET_NAME,
    REC_STRT_DATE1 AS REC_STRT_DATE,
    CAST(NULL AS STRING) AS CTL_REC_CRTN_DATE,
    REC_END_DATE1 AS REC_END_DATE,
    CAST(NULL AS INTEGER) AS CTL_JOB_ID,
    CAST(NULL AS INTEGER) AS CTL_BATCH_ID,
    CAST(NULL AS INTEGER) AS CTL_SRC_ROW_ID,
    CAST(NULL AS INTEGER) AS CTL_EXTRACT_ID,
    CTL_REC_UPDATE_DATE1 AS CTL_REC_UPDATE_DATE,
    PARTY_ID1 AS PARTY_ID,
    CAST(NULL AS STRING) AS FIRST_NAME,
    CAST(NULL AS STRING) AS LAST_NAME,
    CAST(NULL AS STRING) AS EMAIL_ADDR,
    CAST(NULL AS STRING) AS TITLE,
    CAST(NULL AS STRING) AS JOB_TITLE,
    CAST(NULL AS STRING) AS OTHER_NAME,
    CAST(NULL AS STRING) AS GENDER_FLG,
    CAST(NULL AS STRING) AS DOB,
    CAST(NULL AS STRING) AS ABN_LICENCE_NUM,
    CAST(NULL AS STRING) AS BUSN_PHONE_NUM,
    CAST(NULL AS STRING) AS PRIVATE_PHONE_NUM,
    CAST(NULL AS STRING) AS FAX_NUM,
    CAST(NULL AS STRING) AS MOBILE_PHONE_NUM,
    CAST(NULL AS STRING) AS WEB_SITE,
    CAST(NULL AS STRING) AS TAX_FILE_NUM,
    CAST(NULL AS STRING) AS ANZSIC_CODE,
    CAST(NULL AS STRING) AS ACN
  
  FROM RTR_New_SK_New_Existing_party_EXPR_Existing_Party AS in0

),

UNI_New_Existing_Party AS (

  {{
    prophecy_basics.UnionByName(
      [
        'UNI_New_Existing_Party_EXPR_Existing_Update', 
        'UNI_New_Existing_Party_EXPR_Existing_Insert', 
        'UNI_New_Existing_Party_EXPR_New_Insert'
      ], 
      [
        '[{"name": "GEO_SEGMENT_CODE", "dataType": "String"}, {"name": "PARTY_NUM", "dataType": "String"}, {"name": "INTNL_REF_NUM", "dataType": "String"}, {"name": "PARTY_ID_TYPE", "dataType": "String"}, {"name": "INTN_REF_ID_TYPE", "dataType": "String"}, {"name": "PARTY_TYPE_CODE", "dataType": "String"}, {"name": "PERS_CMPY_FLG", "dataType": "String"}, {"name": "CTL_SRC_SYS_SET_NAME", "dataType": "String"}, {"name": "REC_STRT_DATE", "dataType": "Timestamp"}, {"name": "CTL_REC_CRTN_DATE", "dataType": "String"}, {"name": "REC_END_DATE", "dataType": "Timestamp"}, {"name": "CTL_JOB_ID", "dataType": "Integer"}, {"name": "CTL_BATCH_ID", "dataType": "Integer"}, {"name": "CTL_SRC_ROW_ID", "dataType": "Integer"}, {"name": "CTL_EXTRACT_ID", "dataType": "Integer"}, {"name": "CTL_REC_UPDATE_DATE", "dataType": "Timestamp"}, {"name": "PARTY_ID", "dataType": "Integer"}, {"name": "FIRST_NAME", "dataType": "String"}, {"name": "LAST_NAME", "dataType": "String"}, {"name": "EMAIL_ADDR", "dataType": "String"}, {"name": "TITLE", "dataType": "String"}, {"name": "JOB_TITLE", "dataType": "String"}, {"name": "OTHER_NAME", "dataType": "String"}, {"name": "GENDER_FLG", "dataType": "String"}, {"name": "DOB", "dataType": "String"}, {"name": "ABN_LICENCE_NUM", "dataType": "String"}, {"name": "BUSN_PHONE_NUM", "dataType": "String"}, {"name": "PRIVATE_PHONE_NUM", "dataType": "String"}, {"name": "FAX_NUM", "dataType": "String"}, {"name": "MOBILE_PHONE_NUM", "dataType": "String"}, {"name": "WEB_SITE", "dataType": "String"}, {"name": "TAX_FILE_NUM", "dataType": "String"}, {"name": "ANZSIC_CODE", "dataType": "String"}, {"name": "ACN", "dataType": "String"}]', 
        '[{"name": "GEO_SEGMENT_CODE", "dataType": "String"}, {"name": "PARTY_NUM", "dataType": "String"}, {"name": "INTNL_REF_NUM", "dataType": "String"}, {"name": "PARTY_ID_TYPE", "dataType": "String"}, {"name": "INTN_REF_ID_TYPE", "dataType": "String"}, {"name": "PARTY_TYPE_CODE", "dataType": "String"}, {"name": "PERS_CMPY_FLG", "dataType": "String"}, {"name": "CTL_SRC_SYS_SET_NAME", "dataType": "String"}, {"name": "REC_STRT_DATE", "dataType": "Timestamp"}, {"name": "CTL_REC_CRTN_DATE", "dataType": "Timestamp"}, {"name": "REC_END_DATE", "dataType": "Timestamp"}, {"name": "CTL_JOB_ID", "dataType": "Integer"}, {"name": "CTL_BATCH_ID", "dataType": "Integer"}, {"name": "CTL_SRC_ROW_ID", "dataType": "Integer"}, {"name": "CTL_EXTRACT_ID", "dataType": "Integer"}, {"name": "CTL_REC_UPDATE_DATE", "dataType": "String"}, {"name": "PARTY_ID", "dataType": "Integer"}, {"name": "FIRST_NAME", "dataType": "String"}, {"name": "LAST_NAME", "dataType": "String"}, {"name": "EMAIL_ADDR", "dataType": "String"}, {"name": "TITLE", "dataType": "String"}, {"name": "JOB_TITLE", "dataType": "String"}, {"name": "OTHER_NAME", "dataType": "String"}, {"name": "GENDER_FLG", "dataType": "String"}, {"name": "DOB", "dataType": "Timestamp"}, {"name": "ABN_LICENCE_NUM", "dataType": "String"}, {"name": "BUSN_PHONE_NUM", "dataType": "String"}, {"name": "PRIVATE_PHONE_NUM", "dataType": "String"}, {"name": "FAX_NUM", "dataType": "String"}, {"name": "MOBILE_PHONE_NUM", "dataType": "String"}, {"name": "WEB_SITE", "dataType": "String"}, {"name": "TAX_FILE_NUM", "dataType": "String"}, {"name": "ANZSIC_CODE", "dataType": "String"}, {"name": "ACN", "dataType": "String"}]', 
        '[{"name": "GEO_SEGMENT_CODE", "dataType": "String"}, {"name": "PARTY_NUM", "dataType": "String"}, {"name": "INTNL_REF_NUM", "dataType": "String"}, {"name": "PARTY_ID_TYPE", "dataType": "String"}, {"name": "INTN_REF_ID_TYPE", "dataType": "String"}, {"name": "PARTY_TYPE_CODE", "dataType": "String"}, {"name": "PERS_CMPY_FLG", "dataType": "String"}, {"name": "CTL_SRC_SYS_SET_NAME", "dataType": "String"}, {"name": "REC_STRT_DATE", "dataType": "Timestamp"}, {"name": "CTL_REC_CRTN_DATE", "dataType": "Timestamp"}, {"name": "REC_END_DATE", "dataType": "Timestamp"}, {"name": "CTL_JOB_ID", "dataType": "Integer"}, {"name": "CTL_BATCH_ID", "dataType": "Integer"}, {"name": "CTL_SRC_ROW_ID", "dataType": "Integer"}, {"name": "CTL_EXTRACT_ID", "dataType": "Integer"}, {"name": "CTL_REC_UPDATE_DATE", "dataType": "String"}, {"name": "PARTY_ID", "dataType": "Integer"}, {"name": "FIRST_NAME", "dataType": "String"}, {"name": "LAST_NAME", "dataType": "String"}, {"name": "EMAIL_ADDR", "dataType": "String"}, {"name": "TITLE", "dataType": "String"}, {"name": "JOB_TITLE", "dataType": "String"}, {"name": "OTHER_NAME", "dataType": "String"}, {"name": "GENDER_FLG", "dataType": "String"}, {"name": "DOB", "dataType": "Timestamp"}, {"name": "ABN_LICENCE_NUM", "dataType": "String"}, {"name": "BUSN_PHONE_NUM", "dataType": "String"}, {"name": "PRIVATE_PHONE_NUM", "dataType": "String"}, {"name": "FAX_NUM", "dataType": "String"}, {"name": "MOBILE_PHONE_NUM", "dataType": "String"}, {"name": "WEB_SITE", "dataType": "String"}, {"name": "TAX_FILE_NUM", "dataType": "String"}, {"name": "ANZSIC_CODE", "dataType": "String"}, {"name": "ACN", "dataType": "String"}]'
      ], 
      'allowMissingColumns'
    )
  }}

),

UNI_New_Existing_Party_EXPR_200 AS (

  SELECT 
    ACN AS ACN,
    INTN_REF_ID_TYPE AS INTNL_REF_ID_TYPE,
    PARTY_TYPE_CODE AS PARTY_TYPE_CODE,
    PERS_CMPY_FLG AS PERS_CMPY_FLG,
    CTL_SRC_SYS_SET_NAME AS CTL_SRC_SYS_SET_NAME,
    CTL_BATCH_ID AS CTL_BATCH_ID,
    JOB_TITLE AS JOB_TITLE,
    OTHER_NAME AS OTHER_NAME,
    GENDER_FLG AS GENDER_FLG,
    FAX_NUM AS FAX_NUM,
    MOBILE_PHONE_NUM AS MOBILE_PHONE_NUM,
    REC_STRT_DATE AS REC_STRT_DATE,
    CTL_REC_CRTN_DATE AS CTL_REC_CRTN_DATE,
    REC_END_DATE AS REC_END_DATE,
    CTL_JOB_ID AS CTL_JOB_ID,
    DOB AS DOB,
    ABN_LICENCE_NUM AS ABN_LICENCE_NUM,
    BUSN_PHONE_NUM AS BUSN_PHONE_NUM,
    PRIVATE_PHONE_NUM AS PRIVATE_PHONE_NUM,
    GEO_SEGMENT_CODE AS GEO_SEGMENT_CODE,
    CTL_SRC_ROW_ID AS CTL_SRC_ROW_ID,
    CTL_EXTRACT_ID AS CTL_EXTRACT_ID,
    CTL_REC_UPDATE_DATE AS CTL_REC_UPDATE_DATE,
    PARTY_ID AS PARTY_ID,
    FIRST_NAME AS FIRST_NAME,
    LAST_NAME AS LAST_NAME,
    EMAIL_ADDR AS EMAIL_ADDR,
    WEB_SITE AS WEB_SITE,
    TAX_FILE_NUM AS TAX_FILE_NUM,
    TITLE AS TITLE,
    PARTY_NUM AS PARTY_NUM,
    INTNL_REF_NUM AS INTNL_REF_NUM,
    ANZSIC_CODE AS ANZSIC_CODE,
    PARTY_ID_TYPE AS PARTY_ID_TYPE
  
  FROM UNI_New_Existing_Party AS in0

)

SELECT *

FROM UNI_New_Existing_Party_EXPR_200
