{{
  config({    
    "materialized": "ephemeral",
    "database": "qa_team",
    "schema": "qa_orchestration"
  })
}}

WITH `30_MDL_Partymp_cnf_mdl_Party_and_Address_and_SK_sh_P_DIM_PARTY_ADDRESS` AS (

  SELECT *
  
  FROM {{
    prophecy_tmp_source(
      '30_MDL_Party_mp_cnf_mdl_Party_and_Address_and_SK', 
      '30_MDL_Partymp_cnf_mdl_Party_and_Address_and_SK_sh_P_DIM_PARTY_ADDRESS'
    )
  }}

),

EXP_collect_source AS (

  SELECT 
    REC_STRT_DATE AS REC_STRT_DATE,
    GEO_SEGMENT_CODE AS GEO_SEGMENT_CODE,
    PARTY_NUM AS PARTY_NUM,
    INTL_REF_NUM AS INTL_REF_NUM,
    PARTY_ID_TYPE AS PARTY_ID_TYPE,
    INTL_REF_ID_TYPE AS INTL_REF_ID_TYPE,
    PERS_CMPY_FLG AS PERS_CMPY_FLG,
    PARTY_TYPE_CODE AS PARTY_TYPE_CODE,
    FIRST_NAME AS FIRST_NAME,
    LAST_NAME AS LAST_NAME,
    EMAIL_ADDR AS EMAIL_ADDR,
    TITLE AS TITLE,
    JOB_TITLE AS JOB_TITLE,
    OTHER_NAME AS OTHER_NAME,
    GENDER_FLG AS GENDER_FLG,
    DOB AS DOB,
    ABN_LICENCE_NUM AS ABN_LICENCE_NUM,
    BUSN_PHONE_NUM AS BUSN_PHONE_NUM,
    PRIVATE_PHONE_NUM AS PRIVATE_PHONE_NUM,
    FAX_NUM AS FAX_NUM,
    MOBILE_PHONE_NUM AS MOBILE_PHONE_NUM,
    WEB_SITE AS WEB_SITE,
    LCTN AS LCTN,
    DELIVERY_POINT AS DELIVERY_POINT,
    STREET_NO AS STREET_NO,
    STREET_NAME AS STREET_NAME,
    SUBURB AS SUBURB,
    PCODE AS PCODE,
    STATE AS STATE,
    DELIVERY_CODE AS DELIVERY_CODE,
    GEO_CODE AS GEO_CODE,
    ADDR_ROLE_CODE AS ADDR_ROLE_CODE,
    CTL_BATCH_ID AS CTL_BATCH_ID,
    CTL_SRC_ROW_ID AS CTL_SRC_ROW_ID,
    CTL_JOB_ID AS CTL_JOB_ID,
    CTL_REC_CRTN_DATE AS CTL_REC_CRTN_DATE,
    CTL_SRC_SYS_SET_NAME AS CTL_SRC_SYS_SET_NAME,
    CTL_EXTRACT_ID AS CTL_EXTRACT_ID,
    TAX_FILE_NUM AS TAX_FILE_NUM,
    ANZSIC_CODE AS ANZSIC_CODE,
    ACN AS ACN,
    LOCATION_CODE AS LOCATION_CODE,
    GEO_SOURCE AS GEO_SOURCE,
    (monotonically_increasing_id()) AS prophecy_sk,
    REC_STRT_DATE AS IN_TRANSACTION_DATE,
    GEO_SEGMENT_CODE AS IN_GEO_SEGMENT_CODE,
    PARTY_NUM AS IN_PARTY_NUM,
    INTL_REF_NUM AS IN_INTL_REF_NUM,
    PARTY_ID_TYPE AS IN_PARTY_ID_TYPE,
    INTL_REF_ID_TYPE AS IN_INTL_REF_ID_TYPE,
    PERS_CMPY_FLG AS IN_PERS_CMPY_FLG
  
  FROM `30_MDL_Partymp_cnf_mdl_Party_and_Address_and_SK_sh_P_DIM_PARTY_ADDRESS` AS in0

)

SELECT *

FROM EXP_collect_source
