{{
  config({    
    "materialized": "ephemeral",
    "database": "zurich_pov",
    "schema": "zurich"
  })
}}

WITH RTR_New_Existing_SK_JOIN_EXPR_191 AS (

  SELECT *
  
  FROM {{ ref('30_MDL_Party_mp_cnf_mdl_Party_and_Address_and_SK__RTR_New_Existing_SK_JOIN_EXPR_191')}}

),

RTR_New_Existing_SK_out2 AS (

  SELECT * 
  
  FROM RTR_New_Existing_SK_JOIN_EXPR_191 AS in0
  
  WHERE TRUE

),

RTR_New_Existing_SK_EXPR_All AS (

  SELECT 
    REC_STRT_DATE AS REC_STRT_DATE4,
    REC_END_DATE_CLOSED AS REC_END_DATE_CLOSED4,
    REC_END_DATE_HIGH AS REC_END_DATE_HIGH4,
    CTL_REC_CRTN_DATE AS CTL_REC_CRTN_DATE4,
    CTL_JOB_ID AS CTL_JOB_ID4,
    NewLookupRow_SK AS NewLookupRow_SK4,
    GEO_SEGMENT_CODE AS GEO_SEGMENT_CODE4,
    PARTY_NUM AS PARTY_NUM4,
    INTNL_REF_NUM AS INTNL_REF_NUM4,
    PARTY_ID_TYPE AS PARTY_ID_TYPE4,
    INTN_REF_ID_TYPE AS INTN_REF_ID_TYPE4,
    PERS_CMPY_FLG AS PERS_CMPY_FLG4,
    PARTY_ID AS PARTY_ID4,
    PARTY_TYPE_CODE AS PARTY_TYPE_CODE4,
    FIRST_NAME AS FIRST_NAME4,
    LAST_NAME AS LAST_NAME4,
    EMAIL_ADDR AS EMAIL_ADDR4,
    TITLE AS TITLE4,
    JOB_TITLE AS JOB_TITLE4,
    OTHER_NAME AS OTHER_NAME4,
    GENDER_FLG AS GENDER_FLG4,
    DOB AS DOB4,
    ABN_LICENCE_NUM AS ABN_LICENCE_NUM4,
    BUSN_PHONE_NUM AS BUSN_PHONE_NUM4,
    PRIVATE_PHONE_NUM AS PRIVATE_PHONE_NUM4,
    FAX_NUM AS FAX_NUM4,
    MOBILE_PHONE_NUM AS MOBILE_PHONE_NUM4,
    WEB_SITE AS WEB_SITE4,
    OUT_VALID_ADDRESS_FLAG AS OUT_VALID_ADDRESS_FLAG4,
    LCTN AS LCTN4,
    DELIVERY_POINT AS DELIVERY_POINT4,
    STREET_NO AS STREET_NO4,
    STREET_NAME AS STREET_NAME4,
    SUBURB AS SUBURB4,
    PCODE AS PCODE4,
    STATE AS STATE4,
    DELIVERY_CODE AS DELIVERY_CODE4,
    GEO_CODE AS GEO_CODE4,
    ADDR_ROLE_CODE AS ADDR_ROLE_CODE4,
    CTL_BATCH_ID AS CTL_BATCH_ID4,
    CTL_SRC_ROW_ID AS CTL_SRC_ROW_ID4,
    CTL_SRC_SYS_SET_NAME AS CTL_SRC_SYS_SET_NAME4,
    CTL_EXTRACT_ID AS CTL_EXTRACT_ID4,
    TAX_FILE_NUM AS TAX_FILE_NUM4,
    IS_PREF_PARTY_DATA AS IS_PREF_PARTY_DATA4,
    ANZSIC_CODE AS ANZSIC_CODE4,
    ACN AS ACN4,
    LOCATION_CODE AS LOCATION_CODE4,
    GEO_SOURCE AS GEO_SOURCE4,
    CTL_REC_CRTN_DATE AS CTL_REC_CRTN_DATE,
    CTL_JOB_ID AS CTL_JOB_ID,
    REC_STRT_DATE AS REC_STRT_DATE,
    PARTY_ID AS PARTY_ID,
    STREET_NAME AS STREET_NAME,
    SUBURB AS SUBURB,
    PCODE AS PCODE,
    STATE AS STATE,
    CTL_SRC_ROW_ID AS CTL_SRC_ROW_ID,
    CTL_SRC_SYS_SET_NAME AS CTL_SRC_SYS_SET_NAME,
    CTL_EXTRACT_ID AS CTL_EXTRACT_ID,
    REC_END_DATE_CLOSED AS REC_END_DATE_CLOSED,
    OUT_VALID_ADDRESS_FLAG AS OUT_VALID_ADDRESS_FLAG,
    LCTN AS LOCTN,
    DELIVERY_POINT AS DELIVERY_POINT,
    STREET_NO AS STREET_NO,
    DELIVERY_CODE AS DELIVERY_CODE,
    GEO_CODE AS GEO_CODE,
    ADDR_ROLE_CODE AS ADDR_ROLE_CODE,
    CTL_BATCH_ID AS CTL_BATCH_ID,
    REC_END_DATE_HIGH AS REC_END_DATE_HIGH
  
  FROM RTR_New_Existing_SK_out2 AS in0

)

SELECT *

FROM RTR_New_Existing_SK_EXPR_All
