from prophecy_analysis_sdk import *
meta_info = MetaInfo(pipeline_id = "inference_pipeline")

with Analysis(app_id = "inference_pipeline_analysis", meta_info = meta_info) as analysis:
    analysis.text(
        text = "# Customer Churn Prediction Dashboard\n\nThis dashboard displays churn predictions generated by the inference pipeline using the trained ML model."
    )
    analysis.bar_chart(
        source = "churn_summary_by_risk", 
        title = "Customer Count by Churn Risk Level", 
        x_axis_column = "churn_risk", 
        y_axis_columns = [         YAxisColumn(
           name = "customer_id", 
           agg = AggregationType.COUNT, 
           color = "#dc4c4c"
         )], 
        y_axis_config = None
    )
    analysis.pie_chart(
        source = "churn_summary_by_risk", 
        title = "Churn Risk Distribution", 
        x_axis_column = "churn_risk", 
        y_axis_columns = [         YAxisColumn(
           name = "customer_id", 
           agg = AggregationType.COUNT, 
           color = "#4c4ddc"
         )], 
        inner_radius = 50, 
        chart_style = PieStyle.DONUT
    )
    analysis.bar_chart(
        source = "churn_summary_by_risk", 
        title = "Monthly Revenue at Risk by Churn Level", 
        x_axis_column = "churn_risk", 
        y_axis_columns = [         YAxisColumn(
           name = "monthly_charge", 
           agg = AggregationType.SUM, 
           color = "#088ab2"
         )], 
        y_axis_config = None
    )
    analysis.bar_chart(
        source = "churn_predictions_detail", 
        title = "Churn Predictions by Contract Type", 
        x_axis_column = "contract", 
        y_axis_columns = [         YAxisColumn(
           name = "churn_prediction", 
           agg = AggregationType.SUM, 
           color = "#dc4c4c"
         ),          YAxisColumn(
           name = "customer_id", 
           agg = AggregationType.COUNT, 
           color = "#4c4ddc"
         )], 
        y_axis_config = None
    )
    analysis.bar_chart(
        source = "churn_predictions_detail", 
        title = "Churn Predictions by Tenure Category", 
        x_axis_column = "tenure_category", 
        y_axis_columns = [         YAxisColumn(
           name = "churn_prediction", 
           agg = AggregationType.SUM, 
           color = "#dc4c4c"
         ),          YAxisColumn(
           name = "customer_id", 
           agg = AggregationType.COUNT, 
           color = "#088ab2"
         )], 
        y_axis_config = None
    )
    analysis.bar_chart(
        source = "churn_predictions_detail", 
        title = "Average Churn Probability by Age Group", 
        x_axis_column = "age_group", 
        y_axis_columns = [         YAxisColumn(
           name = "churn_probability", 
           color = "#ff9500"
         )], 
        y_axis_config = None
    )
    analysis.data_preview(
        source = "churn_predictions_detail", 
        columns = [Column(column = "customer_id"),  Column(column = "city"),  Column(column = "tenure_in_months"),          Column(column = "contract"),  Column(column = "monthly_charge"),  Column(column = "total_revenue"),          Column(column = "churn_prediction"),  Column(column = "churn_probability"),  Column(column = "churn_risk")], 
        title = "Churn Predictions Detail"
    )
