{{
  config({    
    "materialized": "table",
    "alias": "sh_P_DIM_GI_MESSAGE_from_Message_Document",
    "database": "qa_team",
    "schema": "qa_orchestration"
  })
}}

WITH `20_STG_ZSXmp_src_cnf_P_Dim_GI_Message_SVU_sh_V_ZSX_XML_SVU_MESSAGE_DOCUMENT` AS (

  SELECT *
  
  FROM {{
    prophecy_tmp_source(
      '20_STG_ZSX_mp_src_cnf_P_Dim_GI_Message_SVU', 
      '20_STG_ZSXmp_src_cnf_P_Dim_GI_Message_SVU_sh_V_ZSX_XML_SVU_MESSAGE_DOCUMENT'
    )
  }}

),

SQ_sh_V_ZSX_XML_SVU_MESSAGE_DOCUMENT AS (

  SELECT 
    PARTNER_GATEWAY AS PARTNER_GATEWAY,
    CONVERSATION_NUM AS CONVERSATION_NUM,
    MESSAGE_NUM AS MESSAGE_NUM,
    INTERNAL_ID AS INTERNAL_ID,
    EXCHANGE_STRT_DATE AS EXCHANGE_STRT_DATE,
    SCHEMA_VERSION AS SCHEMA_VERSION,
    EXCHANGE_REFERENCE AS EXCHANGE_REFERENCE,
    _TYPE AS _TYPE,
    CREATED AS CREATED,
    MESSAGE_TYPE_DIRECTION AS MESSAGE_TYPE_DIRECTION,
    OUTBOUND_MESSAGE_TYPE_CODE AS OUTBOUND_MESSAGE_TYPE_CODE,
    INBOUND_MESSAGE_TYPE_CODE AS INBOUND_MESSAGE_TYPE_CODE,
    MESSAGE_PACKET_DOC_TYPE AS MESSAGE_PACKET_DOC_TYPE,
    MESSAGE_TS AS MESSAGE_TS,
    MESSAGE_STATUS_CODE AS MESSAGE_STATUS_CODE,
    MESSAGE_PACKET AS MESSAGE_PACKET,
    CTL_BATCH_ID AS CTL_BATCH_ID,
    CTL_SRC_ROW_ID AS CTL_SRC_ROW_ID,
    CTL_JOB_ID AS CTL_JOB_ID,
    CTL_SRC_SYS_SET_NAME AS CTL_SRC_SYS_SET_NAME,
    CTL_EXTRACT_ID AS CTL_EXTRACT_ID,
    (monotonically_increasing_id()) AS prophecy_sk
  
  FROM `20_STG_ZSXmp_src_cnf_P_Dim_GI_Message_SVU_sh_V_ZSX_XML_SVU_MESSAGE_DOCUMENT` AS in0

),

EXP_Set_Defaults AS (

  SELECT 
    (
      CASE
        WHEN ((EXCHANGE_STRT_DATE IS NULL) OR (CAST((RTRIM((LTRIM(EXCHANGE_STRT_DATE)))) AS string) = ''))
          THEN (MAKE_DATE_TIME(9999, 12, 31, 23, 59, 59, 0))
        ELSE EXCHANGE_STRT_DATE
      END
    ) AS EXCHANGE_STRT_DATE,
    (
      CASE
        WHEN ((SCHEMA_VERSION IS NULL) OR (CAST((RTRIM((LTRIM(SCHEMA_VERSION)))) AS string) = ''))
          THEN '-'
        ELSE SCHEMA_VERSION
      END
    ) AS SCHEMA_VERS,
    (
      CASE
        WHEN ((EXCHANGE_REFERENCE IS NULL) OR (CAST((RTRIM((LTRIM(EXCHANGE_REFERENCE)))) AS string) = ''))
          THEN '-'
        ELSE EXCHANGE_REFERENCE
      END
    ) AS EXCHANGE_REFERENCE,
    'REQUEST_RESPONSE' AS EXCHANGE_PATTERN,
    SUBSTRING(MESSAGE_TYPE_DIRECTION, ((LOCATE('_', MESSAGE_TYPE_DIRECTION, 0)) + 1), 2147483647) AS MESSAGE_TYPE,
    MESSAGE_PACKET AS MESSAGE_PACKET,
    (
      CASE
        WHEN ((MESSAGE_TS IS NULL) OR (CAST((RTRIM((LTRIM(MESSAGE_TS)))) AS string) = ''))
          THEN (MAKE_DATE_TIME(9999, 12, 31, 23, 59, 59, 0))
        ELSE MESSAGE_TS
      END
    ) AS MESSAGE_TS,
    (
      CASE
        WHEN ((MESSAGE_STATUS_CODE IS NULL) OR (CAST((RTRIM((LTRIM(MESSAGE_STATUS_CODE)))) AS string) = ''))
          THEN '-'
        ELSE UPPER(MESSAGE_STATUS_CODE)
      END
    ) AS MESSAGE_STATUS_CODE,
    (
      CASE
        WHEN (CAST(SUBSTRING(MESSAGE_TYPE_DIRECTION, 1, ((LOCATE('_', MESSAGE_TYPE_DIRECTION, 0)) - 1)) AS string) = 'INBOUND')
          THEN (
            CASE
              WHEN CAST((INBOUND_MESSAGE_TYPE_CODE IS NULL) AS BOOLEAN)
                THEN '-'
              ELSE INBOUND_MESSAGE_TYPE_CODE
            END
          )
        WHEN CAST((OUTBOUND_MESSAGE_TYPE_CODE IS NULL) AS BOOLEAN)
          THEN '-'
        ELSE OUTBOUND_MESSAGE_TYPE_CODE
      END
    ) AS MESSAGE_TYPE_CODE,
    (
      CASE
        WHEN (CAST(SUBSTRING(MESSAGE_TYPE_DIRECTION, 1, ((LOCATE('_', MESSAGE_TYPE_DIRECTION, 0)) - 1)) AS string) = 'INBOUND')
          THEN 'IN'
        ELSE 'OUT'
      END
    ) AS MESSAGE_DIRECTION,
    (
      CASE
        WHEN (
          (MESSAGE_PACKET_DOC_TYPE IS NULL)
          OR (CAST((RTRIM((LTRIM(MESSAGE_PACKET_DOC_TYPE)))) AS string) = '')
        )
          THEN '-'
        ELSE MESSAGE_PACKET_DOC_TYPE
      END
    ) AS MESSAGE_PACKET_DOC_TYPE,
    'SVU_GTWY' AS APPLCN_NAME,
    prophecy_sk AS prophecy_sk
  
  FROM SQ_sh_V_ZSX_XML_SVU_MESSAGE_DOCUMENT AS in0

),

EXP_Ctl_Fields_STG AS (

  SELECT 
    CTL_SRC_ROW_ID AS CTL_SRC_ROW_ID,
    CTL_BATCH_ID AS CTL_BATCH_ID,
    CTL_EXTRACT_ID AS CTL_EXTRACT_ID,
    CTL_SRC_SYS_SET_NAME AS CTL_SRC_SYS_SET_NAME,
    {{ var('PMWorkflowRunId') }} AS CTL_JOB_ID,
    CURRENT_TIMESTAMP AS CTL_REC_CRTN_DATE,
    prophecy_sk AS prophecy_sk
  
  FROM SQ_sh_V_ZSX_XML_SVU_MESSAGE_DOCUMENT AS in0

),

sh_P_DIM_GI_MESSAGE_from_Message_Document_EXP_JOIN AS (

  SELECT 
    in0.MESSAGE_PACKET_DOC_TYPE AS MESSAGE_PACKET_DOC_TYPE,
    in1.APPLCN_NAME AS APPLCN_NAME,
    in0.CTL_BATCH_ID AS CTL_BATCH_ID,
    in0.CTL_SRC_SYS_SET_NAME AS CTL_SRC_SYS_SET_NAME,
    in0.INTERNAL_ID AS INTERNAL_ID,
    in1.SCHEMA_VERS AS SCHEMA_VERS,
    in0.MESSAGE_STATUS_CODE AS MESSAGE_STATUS_CODE,
    in0.EXCHANGE_REFERENCE AS EXCHANGE_REFERENCE,
    in0.SCHEMA_VERSION AS SCHEMA_VERSION,
    in1.MESSAGE_TYPE AS MESSAGE_TYPE,
    in2.CTL_REC_CRTN_DATE AS CTL_REC_CRTN_DATE,
    in0.CTL_EXTRACT_ID AS CTL_EXTRACT_ID,
    in0.MESSAGE_TYPE_DIRECTION AS MESSAGE_TYPE_DIRECTION,
    in1.MESSAGE_TYPE_CODE AS MESSAGE_TYPE_CODE,
    in0.MESSAGE_TS AS MESSAGE_TS,
    in0.MESSAGE_NUM AS MESSAGE_NUM,
    in0.CONVERSATION_NUM AS CONVERSATION_NUM,
    in0.prophecy_sk AS prophecy_sk,
    in0.MESSAGE_PACKET AS MESSAGE_PACKET,
    in0.INBOUND_MESSAGE_TYPE_CODE AS INBOUND_MESSAGE_TYPE_CODE,
    in1.MESSAGE_DIRECTION AS MESSAGE_DIRECTION,
    in0.PARTNER_GATEWAY AS PARTNER_GATEWAY,
    in0.EXCHANGE_STRT_DATE AS EXCHANGE_STRT_DATE,
    in1.EXCHANGE_PATTERN AS EXCHANGE_PATTERN,
    in0.OUTBOUND_MESSAGE_TYPE_CODE AS OUTBOUND_MESSAGE_TYPE_CODE,
    in2.CTL_JOB_ID AS CTL_JOB_ID,
    in0.CTL_SRC_ROW_ID AS CTL_SRC_ROW_ID
  
  FROM SQ_sh_V_ZSX_XML_SVU_MESSAGE_DOCUMENT AS in0
  INNER JOIN EXP_Set_Defaults AS in1
     ON (in0.prophecy_sk = in1.prophecy_sk)
  INNER JOIN EXP_Ctl_Fields_STG AS in2
     ON (in1.prophecy_sk = in2.prophecy_sk)

),

sh_P_DIM_GI_MESSAGE_from_Message_Document_EXP AS (

  SELECT 
    CONVERSATION_NUM AS CONVERSATION_NUM,
    INTERNAL_ID AS INTERNAL_ID,
    EXCHANGE_STRT_DATE AS EXCHANGE_STRT_DATE,
    SCHEMA_VERS AS SCHEMA_VERS,
    EXCHANGE_REFERENCE AS EXCHANGE_REFERENCE,
    EXCHANGE_PATTERN AS EXCHANGE_PATTERN,
    MESSAGE_NUM AS MESSAGE_NUM,
    PARTNER_GATEWAY AS PARTNER_GATEWAY,
    CTL_SRC_ROW_ID AS CTL_SRC_ROW_ID,
    CTL_BATCH_ID AS CTL_BATCH_ID,
    CTL_JOB_ID AS CTL_JOB_ID,
    CTL_REC_CRTN_DATE AS CTL_REC_CRTN_DATE,
    CTL_EXTRACT_ID AS CTL_EXTRACT_ID,
    CTL_SRC_SYS_SET_NAME AS CTL_SRC_SYS_SET_NAME,
    MESSAGE_TYPE AS MESSAGE_TYPE,
    MESSAGE_PACKET AS MESSAGE_PACKET,
    MESSAGE_TS AS MESSAGE_TS,
    MESSAGE_STATUS_CODE AS MESSAGE_STATUS_CODE,
    MESSAGE_TYPE_CODE AS MESSAGE_TYPE_CODE,
    MESSAGE_DIRECTION AS MESSAGE_DIRECTION,
    MESSAGE_PACKET_DOC_TYPE AS MESSAGE_PACKET_DOC_TYPE,
    APPLCN_NAME AS APPLCN_NAME,
    CAST(NULL AS string) AS MESSAGE_REPLY_TS,
    prophecy_sk AS prophecy_sk
  
  FROM sh_P_DIM_GI_MESSAGE_from_Message_Document_EXP_JOIN AS in0

)

SELECT *

FROM sh_P_DIM_GI_MESSAGE_from_Message_Document_EXP
