{{
  config({    
    "materialized": "table",
    "alias": "sh_P_DIM_GI_MESSAGE_from_Request_Response",
    "database": "qa_team",
    "schema": "qa_orchestration"
  })
}}

WITH `20_STG_ZSXmp_src_cnf_P_Dim_GI_Message_SVU_sh_V_ZSX_XML_SVU_MESSAGE_REQUEST_RESPONSE` AS (

  SELECT *
  
  FROM {{
    prophecy_tmp_source(
      '20_STG_ZSX_mp_src_cnf_P_Dim_GI_Message_SVU', 
      '20_STG_ZSXmp_src_cnf_P_Dim_GI_Message_SVU_sh_V_ZSX_XML_SVU_MESSAGE_REQUEST_RESPONSE'
    )
  }}

),

SQ_sh_V_ZSX_XML_SVU_MESSAGE_REQUEST_RESPONSE_GENERATE_SK_0 AS (

  SELECT 
    (monotonically_increasing_id()) AS prophecy_sk,
    *
  
  FROM `20_STG_ZSXmp_src_cnf_P_Dim_GI_Message_SVU_sh_V_ZSX_XML_SVU_MESSAGE_REQUEST_RESPONSE` AS in0

),

EXP_Set_Defaults_2 AS (

  SELECT 
    (
      CASE
        WHEN ((EXCHANGE_STRT_DATE IS NULL) OR (CAST((RTRIM((LTRIM(EXCHANGE_STRT_DATE)))) AS string) = ''))
          THEN (MAKE_DATE_TIME(9999, 12, 31, 23, 59, 59, 0))
        ELSE EXCHANGE_STRT_DATE
      END
    ) AS EXCHANGE_STRT_DATE,
    (
      CASE
        WHEN ((SCHEMA_VERSION IS NULL) OR (CAST((RTRIM((LTRIM(SCHEMA_VERSION)))) AS string) = ''))
          THEN '-'
        ELSE SCHEMA_VERSION
      END
    ) AS SCHEMA_VERS,
    (
      CASE
        WHEN ((EXCHANGE_REFERENCE IS NULL) OR (CAST((RTRIM((LTRIM(EXCHANGE_REFERENCE)))) AS string) = ''))
          THEN '-'
        ELSE EXCHANGE_REFERENCE
      END
    ) AS EXCHANGE_REFERENCE,
    'REQUEST_RESPONSE' AS EXCHANGE_PATTERN,
    SUBSTRING(MESSAGE_TYPE_DIRECTION, ((LOCATE('_', MESSAGE_TYPE_DIRECTION, 0)) + 1), 2147483647) AS MESSAGE_TYPE,
    MESSAGE_PACKET AS MESSAGE_PACKET,
    (
      CASE
        WHEN ((IN_MESSAGE_TS IS NULL) OR (CAST((RTRIM((LTRIM(IN_MESSAGE_TS)))) AS string) = ''))
          THEN (MAKE_DATE_TIME(9999, 12, 31, 23, 59, 59, 0))
        ELSE IN_MESSAGE_TS
      END
    ) AS MESSAGE_TS,
    (
      CASE
        WHEN ((MESSAGE_STATUS_CODE IS NULL) OR (CAST((RTRIM((LTRIM(MESSAGE_STATUS_CODE)))) AS string) = ''))
          THEN '-'
        ELSE UPPER(MESSAGE_STATUS_CODE)
      END
    ) AS MESSAGE_STATUS_CODE,
    (
      CASE
        WHEN (CAST(SUBSTRING(MESSAGE_TYPE_DIRECTION, 1, ((LOCATE('_', MESSAGE_TYPE_DIRECTION, 0)) - 1)) AS string) = 'POST_RS')
          THEN RS_MESSAGE_TYPE_CODE
        ELSE RQ_MESSAGE_TYPE_CODE
      END
    ) AS MESSAGE_TYPE_CODE,
    (
      CASE
        WHEN (CAST(SUBSTRING(MESSAGE_TYPE_DIRECTION, 1, ((LOCATE('_', MESSAGE_TYPE_DIRECTION, 0)) - 1)) AS string) = 'INBOUND')
          THEN 'IN'
        ELSE 'OUT'
      END
    ) AS MESSAGE_DIRECTION,
    (
      CASE
        WHEN (
          (MESSAGE_PACKET_DOC_TYPE IS NULL)
          OR (CAST((RTRIM((LTRIM(MESSAGE_PACKET_DOC_TYPE)))) AS string) = '')
        )
          THEN '-'
        ELSE MESSAGE_PACKET_DOC_TYPE
      END
    ) AS MESSAGE_PACKET_DOC_TYPE,
    'SVU_GTWY' AS APPLCN_NAME,
    prophecy_sk AS prophecy_sk
  
  FROM SQ_sh_V_ZSX_XML_SVU_MESSAGE_REQUEST_RESPONSE_GENERATE_SK_0 AS in0

),

EXP_Ctl_Fields_STG_2 AS (

  SELECT 
    CTL_SRC_ROW_ID AS CTL_SRC_ROW_ID,
    CTL_BATCH_ID AS CTL_BATCH_ID,
    CTL_EXTRACT_ID AS CTL_EXTRACT_ID,
    CTL_SRC_SYS_SET_NAME AS CTL_SRC_SYS_SET_NAME,
    {{ var('PMWorkflowRunId') }} AS CTL_JOB_ID,
    CURRENT_TIMESTAMP AS CTL_REC_CRTN_DATE,
    prophecy_sk AS prophecy_sk
  
  FROM SQ_sh_V_ZSX_XML_SVU_MESSAGE_REQUEST_RESPONSE_GENERATE_SK_0 AS in0

),

EXP_Set_Conv_Num AS (

  SELECT 
    (
      CASE
        WHEN (MESSAGE_TYPE_DIRECTION = 'INBOUND_POST_RQ')
          THEN IN_RQ_CONVERSATION_NUM
        WHEN CAST((MESSAGE_TYPE_DIRECTION IN ('INBOUND_POST_RS', 'OUTBOUND_POST_RS')) AS BOOLEAN)
          THEN IN_RS_CONVERSATION_NUM
        ELSE OUT_RQ_CONVERSATION_NUM
      END
    ) AS out_CONVERSATION_NUM,
    prophecy_sk AS prophecy_sk
  
  FROM SQ_sh_V_ZSX_XML_SVU_MESSAGE_REQUEST_RESPONSE_GENERATE_SK_0 AS in0

),

sh_P_DIM_GI_MESSAGE_from_Request_Response_EXP_JOIN AS (

  SELECT 
    in2.MESSAGE_PACKET_DOC_TYPE AS MESSAGE_PACKET_DOC_TYPE,
    in2.APPLCN_NAME AS APPLCN_NAME,
    in3.CTL_BATCH_ID AS CTL_BATCH_ID,
    in3.CTL_SRC_SYS_SET_NAME AS CTL_SRC_SYS_SET_NAME,
    in0.INTERNAL_ID AS INTERNAL_ID,
    in2.SCHEMA_VERS AS SCHEMA_VERS,
    in1.out_CONVERSATION_NUM AS out_CONVERSATION_NUM,
    in2.MESSAGE_STATUS_CODE AS MESSAGE_STATUS_CODE,
    in2.EXCHANGE_REFERENCE AS EXCHANGE_REFERENCE,
    in2.MESSAGE_TYPE AS MESSAGE_TYPE,
    in3.CTL_REC_CRTN_DATE AS CTL_REC_CRTN_DATE,
    in3.CTL_EXTRACT_ID AS CTL_EXTRACT_ID,
    in2.MESSAGE_TYPE_CODE AS MESSAGE_TYPE_CODE,
    in2.MESSAGE_TS AS MESSAGE_TS,
    in0.MESSAGE_NUM AS MESSAGE_NUM,
    in0.prophecy_sk AS prophecy_sk,
    in2.MESSAGE_PACKET AS MESSAGE_PACKET,
    in2.MESSAGE_DIRECTION AS MESSAGE_DIRECTION,
    in0.PARTNER_GATEWAY AS PARTNER_GATEWAY,
    in2.EXCHANGE_STRT_DATE AS EXCHANGE_STRT_DATE,
    in2.EXCHANGE_PATTERN AS EXCHANGE_PATTERN,
    in3.CTL_JOB_ID AS CTL_JOB_ID,
    in3.CTL_SRC_ROW_ID AS CTL_SRC_ROW_ID
  
  FROM SQ_sh_V_ZSX_XML_SVU_MESSAGE_REQUEST_RESPONSE_GENERATE_SK_0 AS in0
  INNER JOIN EXP_Set_Conv_Num AS in1
     ON (in0.prophecy_sk = in1.prophecy_sk)
  INNER JOIN EXP_Set_Defaults_2 AS in2
     ON (in1.prophecy_sk = in2.prophecy_sk)
  INNER JOIN EXP_Ctl_Fields_STG_2 AS in3
     ON (in2.prophecy_sk = in3.prophecy_sk)

),

sh_P_DIM_GI_MESSAGE_from_Request_Response_EXP AS (

  SELECT 
    out_CONVERSATION_NUM AS CONVERSATION_NUM,
    INTERNAL_ID AS INTERNAL_ID,
    EXCHANGE_STRT_DATE AS EXCHANGE_STRT_DATE,
    SCHEMA_VERS AS SCHEMA_VERS,
    EXCHANGE_REFERENCE AS EXCHANGE_REFERENCE,
    EXCHANGE_PATTERN AS EXCHANGE_PATTERN,
    MESSAGE_NUM AS MESSAGE_NUM,
    PARTNER_GATEWAY AS PARTNER_GATEWAY,
    CTL_SRC_ROW_ID AS CTL_SRC_ROW_ID,
    CTL_BATCH_ID AS CTL_BATCH_ID,
    CTL_JOB_ID AS CTL_JOB_ID,
    CTL_REC_CRTN_DATE AS CTL_REC_CRTN_DATE,
    CTL_EXTRACT_ID AS CTL_EXTRACT_ID,
    CTL_SRC_SYS_SET_NAME AS CTL_SRC_SYS_SET_NAME,
    MESSAGE_TYPE AS MESSAGE_TYPE,
    MESSAGE_PACKET AS MESSAGE_PACKET,
    MESSAGE_TS AS MESSAGE_TS,
    MESSAGE_STATUS_CODE AS MESSAGE_STATUS_CODE,
    MESSAGE_TYPE_CODE AS MESSAGE_TYPE_CODE,
    MESSAGE_DIRECTION AS MESSAGE_DIRECTION,
    MESSAGE_PACKET_DOC_TYPE AS MESSAGE_PACKET_DOC_TYPE,
    APPLCN_NAME AS APPLCN_NAME,
    CAST(NULL AS string) AS MESSAGE_REPLY_TS,
    prophecy_sk AS prophecy_sk
  
  FROM sh_P_DIM_GI_MESSAGE_from_Request_Response_EXP_JOIN AS in0

)

SELECT *

FROM sh_P_DIM_GI_MESSAGE_from_Request_Response_EXP
