{{
  config({    
    "materialized": "table",
    "alias": "Dim_Claim_Temp",
    "database": "qa_team",
    "schema": "qa_orchestration"
  })
}}

WITH `40_DM_ORACmp_s_dim_claim_temp_SQ_V_Dim_Claim_Temp_Claimant` AS (

  SELECT *
  
  FROM {{
    prophecy_tmp_source(
      '40_DM_ORAC_mp_s_dim_claim_temp', 
      '40_DM_ORACmp_s_dim_claim_temp_SQ_V_Dim_Claim_Temp_Claimant'
    )
  }}

),

`40_DM_ORACmp_s_dim_claim_temp_SQ_V_Dim_Claim_Temp_CA` AS (

  SELECT *
  
  FROM {{
    prophecy_tmp_source(
      '40_DM_ORAC_mp_s_dim_claim_temp', 
      '40_DM_ORACmp_s_dim_claim_temp_SQ_V_Dim_Claim_Temp_CA'
    )
  }}

),

`40_DM_ORACmp_s_dim_claim_temp_SQ_V_Dim_Claim_Temp_WC_MT_LIA` AS (

  SELECT *
  
  FROM {{
    prophecy_tmp_source(
      '40_DM_ORAC_mp_s_dim_claim_temp', 
      '40_DM_ORACmp_s_dim_claim_temp_SQ_V_Dim_Claim_Temp_WC_MT_LIA'
    )
  }}

),

Srt_Claimant_EXPR_357 AS (

  SELECT 
    Claim_Key AS Claim_Key2,
    Claimant_Name AS Claimant_Name,
    Claim_Motor_Driver_Name AS Claim_Motor_Driver_Name,
    Claim_Motor_Driver_Names_Text AS Claim_Motor_Driver_Names_Text
  
  FROM `40_DM_ORACmp_s_dim_claim_temp_SQ_V_Dim_Claim_Temp_Claimant` AS in0

),

SQ_V_Dim_Claim_Temp_WC_MT_LIA_EXPR_358 AS (

  SELECT 
    Claim_WC_IMA_Reviewed_YN AS Claim_WC_IMA_Reviewed_YN,
    Claim_WC_Injury_Mechanism_Key AS Claim_WC_Injury_Mechanism_Key,
    Claim_WC_Injury_Nature_Key AS Claim_WC_Injury_Nature_Key,
    Claim_WC_Fitness_Level_Code AS Claim_WC_Fitness_Level_Code,
    Claim_WC_Lost_Hours_Number AS Claim_WC_Lost_Hours_Number,
    Claim_WC_Lost_Minutes_Number AS Claim_WC_Lost_Minutes_Number,
    Claim_WC_Injury_Most_Serious_Description AS Claim_WC_Injury_Most_Serious_Description,
    Claim_WC_Injury_Object_Involved_Name AS Claim_WC_Injury_Object_Involved_Name,
    Claim_WC_Work_Resumed_Date_Key AS Claim_WC_Work_Resumed_Date_Key,
    Claim_WC_Loss_Time_Number AS Claim_WC_Loss_Time_Number,
    Claim_WC_Department_Name AS Claim_WC_Department_Name,
    Claim_WC_Worker_Name AS Claim_WC_Worker_Name,
    ASCO_Key AS ASCO_Key,
    Industry_Class_ANZSIC_2006_Key AS Industry_Class_ANZSIC_2006_Key,
    Claim_Liability_Law_Costs_YN AS Claim_Liability_Law_Costs_YN,
    Claim_Liability_Other_Damages_YN AS Claim_Liability_Other_Damages_YN,
    Claim_Liability_Cause_Code AS Claim_Liability_Cause_Code,
    Claim_Liability_Severity_Code AS Claim_Liability_Severity_Code,
    Claim_Liability_Litigation_Status_Code AS Claim_Liability_Litigation_Status_Code,
    Claim_Liability_Property_Damage_YN AS Claim_Liability_Property_Damage_YN,
    Claim_Liability_Financial_Loss_YN AS Claim_Liability_Financial_Loss_YN,
    Claim_WC_Received_Date_by_Employer AS Claim_WC_Received_Date_by_Employer,
    Claim_WC_Work_Status AS Claim_WC_Work_Status,
    Claim_Duty_Status AS Claim_Duty_Status,
    Claim_Key AS Claim_Key1,
    Claim_Liability_Personal_Injury_YN AS Claim_Liability_Personal_Injury_YN,
    Claim_Division_Name AS Claim_Division_Name,
    Claim_Motor_Fault_Key AS Claim_Motor_Fault_Key,
    Claim_Motor_Vehicle_Class_Key AS Claim_Motor_Vehicle_Class_Key,
    Claim_Motor_Bodily_Injury_YN AS Claim_Motor_Bodily_Injury_YN,
    Claim_Motor_Vehicle_Loss_Day_of_Week_Code AS Claim_Motor_Vehicle_Loss_Day_of_Week_Code,
    Claim_Motor_Vehicle_Loss_Time_Number AS Claim_Motor_Vehicle_Loss_Time_Number,
    Claim_Motor_Cost_Centre_Name AS Claim_Motor_Cost_Centre_Name,
    Claim_Motor_Driver_Age_Years_Number AS Claim_Motor_Driver_Age_Years_Number,
    Claim_Motor_Vehicle_Finance_YN AS Claim_Motor_Vehicle_Finance_YN,
    Claim_Motor_Vehicle_Rego_Code AS Claim_Motor_Vehicle_Rego_Code,
    Claim_Motor_Vehicle_Total_Loss_YN AS Claim_Motor_Vehicle_Total_Loss_YN,
    Claim_Motor_Vehicle_Description AS Claim_Motor_Vehicle_Description,
    Claim_Motor_Vehicle_Usage_Code AS Claim_Motor_Vehicle_Usage_Code,
    Claim_Motor_Driver_Licensed_Years_Number AS Claim_Motor_Driver_Licensed_Years_Number,
    Claim_Motor_Vehicle_Manufactured_Year_Number AS Claim_Motor_Vehicle_Manufactured_Year_Number,
    Claim_Motor_Driver_Gender_Code AS Claim_Motor_Driver_Gender_Code,
    Claim_WC_Worker_Suburb_Name AS Claim_WC_Worker_Suburb_Name,
    Claim_WC_Worker_State_Code AS Claim_WC_Worker_State_Code,
    Claim_WC_Worker_Postcode AS Claim_WC_Worker_Postcode,
    Claim_WC_Gender_Code AS Claim_WC_Gender_Code,
    Claim_WC_Birth_Date_Key AS Claim_WC_Birth_Date_Key,
    Claim_WC_Marital_Status_Code AS Claim_WC_Marital_Status_Code,
    Claim_WC_Full_Time_Part_Time_Code AS Claim_WC_Full_Time_Part_Time_Code,
    Claim_WC_Hourly_Rate_First_13_Weeks_Amount AS Claim_WC_Hourly_Rate_First_13_Weeks_Amount,
    Claim_WC_Hourly_Rate_Thereafter_Amount AS Claim_WC_Hourly_Rate_Thereafter_Amount,
    Claim_WC_Worker_Weekly_Hours_Rate AS Claim_WC_Worker_Weekly_Hours_Rate,
    Claim_WC_Worker_Weekly_Hours_Time AS Claim_WC_Worker_Weekly_Hours_Time,
    Claim_WC_Occupation_Name AS Claim_WC_Occupation_Name,
    Claim_WC_Classification_Code AS Claim_WC_Classification_Code,
    Claim_WC_Body_Location_Key AS Claim_WC_Body_Location_Key,
    Claim_WC_Agency_of_Accident_Key AS Claim_WC_Agency_of_Accident_Key,
    Claim_WC_Breakdown_Agency_Key AS Claim_WC_Breakdown_Agency_Key,
    Claim_WC_Ceased_Work_Date_Key AS Claim_WC_Ceased_Work_Date_Key,
    Claim_WC_Common_Law_Raised_Date_Key AS Claim_WC_Common_Law_Raised_Date_Key,
    Claim_WC_Common_Law_Outcome_Code AS Claim_WC_Common_Law_Outcome_Code,
    Claim_WC_Common_Law_Severity_Code AS Claim_WC_Common_Law_Severity_Code,
    Claim_WC_Medical_Certificate_Last_Date_Key AS Claim_WC_Medical_Certificate_Last_Date_Key,
    Claim_WC_Loss_Day_of_Week_Code AS Claim_WC_Loss_Day_of_Week_Code,
    Claim_WC_Estimated_Return_Date_Key AS Claim_WC_Estimated_Return_Date_Key,
    Claim_WC_IMA_Date_Key AS Claim_WC_IMA_Date_Key,
    Claim_WC_Worker_RTW_Program AS Claim_WC_Worker_RTW_Program,
    Claim_WC_Worker_RTW_Goals AS Claim_WC_Worker_RTW_Goals
  
  FROM `40_DM_ORACmp_s_dim_claim_temp_SQ_V_Dim_Claim_Temp_WC_MT_LIA` AS in0

),

SQ_V_Dim_Claim_Temp_CA_EXPR_360 AS (

  SELECT 
    Claim_Key AS Claim_Key,
    Claim_Number AS Claim_Number,
    Claim_Cause_of_Loss_Description AS Claim_Cause_of_Loss_Description,
    Claim_Postcode AS Claim_Postcode,
    Claim_UX_Type_Code AS Claim_UX_Type_Code,
    Claim_UX_Arrangement_Description AS Claim_UX_Arrangement_Description,
    Claim_Salvage_YN AS Claim_Salvage_YN,
    Claim_Recovery_YN AS Claim_Recovery_YN,
    Company_Key AS Company_Key,
    Claim_Branch_Key AS Claim_Branch_Key,
    Premium_Class_Key AS Premium_Class_Key,
    Product_Key AS Product_Key,
    Global_LoB_Key AS Global_LoB_Key,
    Claim_Reported_Date_Key AS Claim_Reported_Date_Key,
    Claim_Expiry_Date_Key AS Claim_Expiry_Date_Key,
    Claim_Loss_Date_Key AS Claim_Loss_Date_Key,
    Claim_Indemnity_Decision_Key AS Claim_Indemnity_Decision_Key,
    Claim_Indemnity_Decision_Date_Key AS Claim_Indemnity_Decision_Date_Key,
    Claim_Status_Date_Key AS Claim_Status_Date_Key,
    Claim_Solicitor_Key AS Claim_Solicitor_Key,
    Claim_Assessor_Key AS Claim_Assessor_Key,
    Claim_Investigator_Key AS Claim_Investigator_Key,
    Catastrophe_Event_ICA_Key AS Catastrophe_Event_ICA_Key,
    Claim_Handler_Key AS Claim_Handler_Key,
    Policy_Key AS Policy_Key,
    Claim_Portfolio_Key AS Claim_Portfolio_Key,
    Risk_Key AS Risk_Key,
    Claim_Reopened_YN AS Claim_Reopened_YN,
    Claim_Notified_Date_Key AS Claim_Notified_Date_Key,
    Claim_State_Code AS Claim_State_Code,
    Claim_Type_Key AS Claim_Type_Key,
    Claim_Status_Key AS Claim_Status_Key,
    Risk_Class_Key AS Risk_Class_Key,
    Broker_Account_Key AS Broker_Account_Key,
    Client_Key AS Client_Key,
    Policy_Incep_Date_Key AS Policy_Incep_Date_Key,
    Policy_Period_Name AS Policy_Period_Name,
    Claim_Closed_Date_Key AS Claim_Closed_Date_Key,
    Claim_Non_Standard_Type_Key AS Claim_Non_Standard_Type_Key,
    Claim_Reopened_Last_Date_Key AS Claim_Reopened_Last_Date_Key,
    Claim_Date_Accepted_Key AS Claim_Date_Accepted_Key,
    Claim_Date_Rejected_Key AS Claim_Date_Rejected_Key,
    Industry_Class_ANZSIC_93_Key AS Industry_Class_ANZSIC_93_Key,
    Claim_Liability_Status_Code AS Claim_Liability_Status_Code,
    Claim_Liability_Date_Key AS Claim_Liability_Date_Key,
    Claim_Agg_Arrangement_Type_Key AS Claim_Agg_Arrangement_Type_Key,
    Claim_Agg_Arrangement_Key AS Claim_Agg_Arrangement_Key,
    Claim_Loss_Location_Key AS Claim_Loss_Location_Key,
    Claim_BGC_Status_Code AS Claim_BGC_Status_Code,
    Claim_Loss_Date_Difference_Days_Number AS Claim_Loss_Date_Difference_Days_Number,
    Claim_Loss_Date_Modified_Date_Key AS Claim_Loss_Date_Modified_Date_Key,
    Claim_Loss_Date_Modified_User_Key AS Claim_Loss_Date_Modified_User_Key,
    Claim_Loss_Date_Modified_YN AS Claim_Loss_Date_Modified_YN,
    Claim_Loss_Orig_Date_Key AS Claim_Loss_Orig_Date_Key,
    Claim_Recovery_Abandonment_Reason_Key AS Claim_Recovery_Abandonment_Reason_Key,
    Claim_Recovery_Changed_YN AS Claim_Recovery_Changed_YN,
    Claim_Recovery_Changed_Date_Key AS Claim_Recovery_Changed_Date_Key,
    Claim_Updated_Datetime AS Claim_Updated_Datetime,
    Claim_Updated_Date_Key AS Claim_Updated_Date_Key,
    Claim_Updated_User_Key AS Claim_Updated_User_Key,
    Claim_Duplicate_Status_Key AS Claim_Duplicate_Status_Key,
    Claim_Fraud_Type_Key AS Claim_Fraud_Type_Key,
    Claim_Duplicate_Loss_Days_Tolerance_Key AS Claim_Duplicate_Loss_Days_Tolerance_Key,
    Claim_Duplicate_Loss_Days_Number AS Claim_Duplicate_Loss_Days_Number,
    Claim_Duplicate_Potential_YN AS Claim_Duplicate_Potential_YN,
    Claim_Duplicate_Potential_Key AS Claim_Duplicate_Potential_Key,
    Claim_Gross_Incurred_Loss_Type_Key AS Claim_Gross_Incurred_Loss_Type_Key,
    Client_Claim_Number AS Client_Claim_Number,
    Claim_Vulnerable_Flag AS Claim_vulnerable_flag,
    Claim_Time_Occurence AS Claim_Time_Occurence,
    Claim_Cyclone_Flag AS Claim_Cyclone_Flag,
    ARPC_Incident_Number AS ARPC_Incident_Number
  
  FROM `40_DM_ORACmp_s_dim_claim_temp_SQ_V_Dim_Claim_Temp_CA` AS in0

),

Jnr_Claim_CA_WC_LIA AS (

  SELECT 
    in1.Claim_Loss_Date_Modified_User_Key AS Claim_Loss_Date_Modified_User_Key,
    in0.Claim_WC_Department_Name AS Claim_WC_Department_Name,
    in1.Claim_Notified_Date_Key AS Claim_Notified_Date_Key,
    in0.Claim_WC_Injury_Object_Involved_Name AS Claim_WC_Injury_Object_Involved_Name,
    in0.Claim_WC_Worker_Postcode AS Claim_WC_Worker_Postcode,
    in0.Claim_WC_Medical_Certificate_Last_Date_Key AS Claim_WC_Medical_Certificate_Last_Date_Key,
    in1.Claim_Duplicate_Loss_Days_Tolerance_Key AS Claim_Duplicate_Loss_Days_Tolerance_Key,
    in1.Claim_Reopened_YN AS Claim_Reopened_YN,
    in0.Claim_Liability_Other_Damages_YN AS Claim_Liability_Other_Damages_YN,
    in1.Claim_Solicitor_Key AS Claim_Solicitor_Key,
    in1.Claim_Indemnity_Decision_Key AS Claim_Indemnity_Decision_Key,
    in1.Claim_Reported_Date_Key AS Claim_Reported_Date_Key,
    in0.Claim_Liability_Litigation_Status_Code AS Claim_Liability_Litigation_Status_Code,
    in0.Claim_WC_Loss_Time_Number AS Claim_WC_Loss_Time_Number,
    in1.Claim_Key AS Claim_Key,
    in1.Company_Key AS Company_Key,
    in0.Claim_WC_IMA_Date_Key AS Claim_WC_IMA_Date_Key,
    in0.Claim_WC_Breakdown_Agency_Key AS Claim_WC_Breakdown_Agency_Key,
    in0.Claim_Motor_Vehicle_Usage_Code AS Claim_Motor_Vehicle_Usage_Code,
    in0.Claim_WC_Classification_Code AS Claim_WC_Classification_Code,
    in0.Claim_Key1 AS Claim_Key1,
    in1.Claim_Indemnity_Decision_Date_Key AS Claim_Indemnity_Decision_Date_Key,
    in0.Claim_Motor_Fault_Key AS Claim_Motor_Fault_Key,
    in0.Claim_Liability_Cause_Code AS Claim_Liability_Cause_Code,
    in1.Claim_Cause_of_Loss_Description AS Claim_Cause_of_Loss_Description,
    in0.Claim_Liability_Law_Costs_YN AS Claim_Liability_Law_Costs_YN,
    in1.Claim_Updated_User_Key AS Claim_Updated_User_Key,
    in1.Claim_Loss_Date_Modified_Date_Key AS Claim_Loss_Date_Modified_Date_Key,
    in1.Risk_Class_Key AS Risk_Class_Key,
    in1.Claim_Number AS Claim_Number,
    in0.Claim_WC_Gender_Code AS Claim_WC_Gender_Code,
    in0.Claim_Motor_Vehicle_Class_Key AS Claim_Motor_Vehicle_Class_Key,
    in1.Claim_Postcode AS Claim_Postcode,
    in0.Claim_WC_Injury_Mechanism_Key AS Claim_WC_Injury_Mechanism_Key,
    in1.Claim_Recovery_Changed_Date_Key AS Claim_Recovery_Changed_Date_Key,
    in1.Claim_Loss_Location_Key AS Claim_Loss_Location_Key,
    in0.ASCO_Key AS ASCO_Key,
    in0.Claim_WC_Fitness_Level_Code AS Claim_WC_Fitness_Level_Code,
    in1.Industry_Class_ANZSIC_93_Key AS Industry_Class_ANZSIC_93_Key,
    in0.Claim_WC_Injury_Nature_Key AS Claim_WC_Injury_Nature_Key,
    in1.Claim_Duplicate_Status_Key AS Claim_Duplicate_Status_Key,
    in0.Claim_Liability_Property_Damage_YN AS Claim_Liability_Property_Damage_YN,
    in1.Claim_Loss_Date_Difference_Days_Number AS Claim_Loss_Date_Difference_Days_Number,
    in1.Claim_Date_Accepted_Key AS Claim_Date_Accepted_Key,
    in1.Claim_Liability_Date_Key AS Claim_Liability_Date_Key,
    in0.Claim_Liability_Personal_Injury_YN AS Claim_Liability_Personal_Injury_YN,
    in1.Catastrophe_Event_ICA_Key AS Catastrophe_Event_ICA_Key,
    in0.Claim_WC_Common_Law_Outcome_Code AS Claim_WC_Common_Law_Outcome_Code,
    in0.Claim_WC_Worker_Weekly_Hours_Time AS Claim_WC_Worker_Weekly_Hours_Time,
    in0.Claim_WC_Received_Date_by_Employer AS Claim_WC_Received_Date_by_Employer,
    in0.Claim_Motor_Vehicle_Manufactured_Year_Number AS Claim_Motor_Vehicle_Manufactured_Year_Number,
    in1.Broker_Account_Key AS Broker_Account_Key,
    in0.Claim_WC_Work_Resumed_Date_Key AS Claim_WC_Work_Resumed_Date_Key,
    in0.Claim_WC_Occupation_Name AS Claim_WC_Occupation_Name,
    in1.Claim_Updated_Date_Key AS Claim_Updated_Date_Key,
    in1.Policy_Key AS Policy_Key,
    in1.Claim_Type_Key AS Claim_Type_Key,
    in0.Claim_Liability_Severity_Code AS Claim_Liability_Severity_Code,
    in0.Claim_Motor_Cost_Centre_Name AS Claim_Motor_Cost_Centre_Name,
    in1.Premium_Class_Key AS Premium_Class_Key,
    in1.Claim_Agg_Arrangement_Key AS Claim_Agg_Arrangement_Key,
    in1.ARPC_Incident_Number AS ARPC_Incident_Number,
    in0.Claim_Motor_Driver_Gender_Code AS Claim_Motor_Driver_Gender_Code,
    in1.Claim_Liability_Status_Code AS Claim_Liability_Status_Code,
    in1.Claim_Recovery_YN AS Claim_Recovery_YN,
    in1.Product_Key AS Product_Key,
    in1.Claim_Salvage_YN AS Claim_Salvage_YN,
    in1.Claim_Duplicate_Loss_Days_Number AS Claim_Duplicate_Loss_Days_Number,
    in1.Claim_Duplicate_Potential_YN AS Claim_Duplicate_Potential_YN,
    in0.Claim_WC_Injury_Most_Serious_Description AS Claim_WC_Injury_Most_Serious_Description,
    in0.Claim_Liability_Financial_Loss_YN AS Claim_Liability_Financial_Loss_YN,
    in0.Industry_Class_ANZSIC_2006_Key AS Industry_Class_ANZSIC_2006_Key,
    in1.Risk_Key AS Risk_Key,
    in1.Claim_Investigator_Key AS Claim_Investigator_Key,
    in1.Claim_Agg_Arrangement_Type_Key AS Claim_Agg_Arrangement_Type_Key,
    in0.Claim_Motor_Vehicle_Description AS Claim_Motor_Vehicle_Description,
    in0.Claim_WC_Marital_Status_Code AS Claim_WC_Marital_Status_Code,
    in0.Claim_WC_Worker_Name AS Claim_WC_Worker_Name,
    in0.Claim_Duty_Status AS Claim_Duty_Status,
    in0.Claim_WC_Worker_Weekly_Hours_Rate AS Claim_WC_Worker_Weekly_Hours_Rate,
    in1.Claim_Branch_Key AS Claim_Branch_Key,
    in0.Claim_WC_Hourly_Rate_Thereafter_Amount AS Claim_WC_Hourly_Rate_Thereafter_Amount,
    in1.Claim_Fraud_Type_Key AS Claim_Fraud_Type_Key,
    in0.Claim_Motor_Vehicle_Rego_Code AS Claim_Motor_Vehicle_Rego_Code,
    in1.Claim_Portfolio_Key AS Claim_Portfolio_Key,
    in0.Claim_Motor_Bodily_Injury_YN AS Claim_Motor_Bodily_Injury_YN,
    in1.Claim_Loss_Date_Modified_YN AS Claim_Loss_Date_Modified_YN,
    in0.Claim_WC_Lost_Minutes_Number AS Claim_WC_Lost_Minutes_Number,
    in1.Claim_Gross_Incurred_Loss_Type_Key AS Claim_Gross_Incurred_Loss_Type_Key,
    in0.Claim_WC_Lost_Hours_Number AS Claim_WC_Lost_Hours_Number,
    in1.Client_Claim_Number AS Client_Claim_Number,
    in0.Claim_WC_Work_Status AS Claim_WC_Work_Status,
    in0.Claim_WC_Estimated_Return_Date_Key AS Claim_WC_Estimated_Return_Date_Key,
    in1.Global_LoB_Key AS Global_LoB_Key,
    in1.Policy_Period_Name AS Policy_Period_Name,
    in1.Claim_Recovery_Abandonment_Reason_Key AS Claim_Recovery_Abandonment_Reason_Key,
    in1.Claim_Handler_Key AS Claim_Handler_Key,
    in1.Claim_Updated_Datetime AS Claim_Updated_Datetime,
    in1.Claim_BGC_Status_Code AS Claim_BGC_Status_Code,
    in0.Claim_WC_Common_Law_Raised_Date_Key AS Claim_WC_Common_Law_Raised_Date_Key,
    in1.Claim_Reopened_Last_Date_Key AS Claim_Reopened_Last_Date_Key,
    in1.Client_Key AS Client_Key,
    in1.Claim_Date_Rejected_Key AS Claim_Date_Rejected_Key,
    in0.Claim_WC_Full_Time_Part_Time_Code AS Claim_WC_Full_Time_Part_Time_Code,
    in0.Claim_WC_Worker_State_Code AS Claim_WC_Worker_State_Code,
    in0.Claim_Motor_Vehicle_Finance_YN AS Claim_Motor_Vehicle_Finance_YN,
    in0.Claim_WC_Worker_Suburb_Name AS Claim_WC_Worker_Suburb_Name,
    in0.Claim_Motor_Vehicle_Loss_Day_of_Week_Code AS Claim_Motor_Vehicle_Loss_Day_of_Week_Code,
    in1.Claim_Cyclone_Flag AS Claim_Cyclone_Flag,
    in1.Claim_UX_Type_Code AS Claim_UX_Type_Code,
    in0.Claim_Motor_Driver_Licensed_Years_Number AS Claim_Motor_Driver_Licensed_Years_Number,
    in0.Claim_Division_Name AS Claim_Division_Name,
    in1.Claim_Expiry_Date_Key AS Claim_Expiry_Date_Key,
    in1.Claim_Status_Key AS Claim_Status_Key,
    in1.Claim_Time_Occurence AS Claim_Time_Occurence,
    in0.Claim_WC_IMA_Reviewed_YN AS Claim_WC_IMA_Reviewed_YN,
    in0.Claim_WC_Worker_RTW_Program AS Claim_WC_Worker_RTW_Program,
    in1.Claim_Loss_Date_Key AS Claim_Loss_Date_Key,
    in1.Claim_Closed_Date_Key AS Claim_Closed_Date_Key,
    in0.Claim_WC_Birth_Date_Key AS Claim_WC_Birth_Date_Key,
    in0.Claim_WC_Hourly_Rate_First_13_Weeks_Amount AS Claim_WC_Hourly_Rate_First_13_Weeks_Amount,
    in1.Claim_Non_Standard_Type_Key AS Claim_Non_Standard_Type_Key,
    in0.Claim_Motor_Vehicle_Total_Loss_YN AS Claim_Motor_Vehicle_Total_Loss_YN,
    in0.Claim_WC_Ceased_Work_Date_Key AS Claim_WC_Ceased_Work_Date_Key,
    in0.Claim_WC_Common_Law_Severity_Code AS Claim_WC_Common_Law_Severity_Code,
    in0.Claim_WC_Agency_of_Accident_Key AS Claim_WC_Agency_of_Accident_Key,
    in0.Claim_WC_Worker_RTW_Goals AS Claim_WC_Worker_RTW_Goals,
    in1.Claim_Loss_Orig_Date_Key AS Claim_Loss_Orig_Date_Key,
    in1.Policy_Incep_Date_Key AS Policy_Incep_Date_Key,
    in1.Claim_Duplicate_Potential_Key AS Claim_Duplicate_Potential_Key,
    in0.Claim_Motor_Vehicle_Loss_Time_Number AS Claim_Motor_Vehicle_Loss_Time_Number,
    in1.Claim_vulnerable_flag AS Claim_vulnerable_flag,
    in1.Claim_Status_Date_Key AS Claim_Status_Date_Key,
    in0.Claim_Motor_Driver_Age_Years_Number AS Claim_Motor_Driver_Age_Years_Number,
    in0.Claim_WC_Loss_Day_of_Week_Code AS Claim_WC_Loss_Day_of_Week_Code,
    in0.Claim_WC_Body_Location_Key AS Claim_WC_Body_Location_Key,
    in1.Claim_State_Code AS Claim_State_Code,
    in1.Claim_Recovery_Changed_YN AS Claim_Recovery_Changed_YN,
    in1.Claim_Assessor_Key AS Claim_Assessor_Key,
    in1.Claim_UX_Arrangement_Description AS Claim_UX_Arrangement_Description
  
  FROM SQ_V_Dim_Claim_Temp_WC_MT_LIA_EXPR_358 AS in0
  INNER JOIN SQ_V_Dim_Claim_Temp_CA_EXPR_360 AS in1
     ON (in0.Claim_Key1 = in1.Claim_Key)

),

Jnr_Claim_CA_WC_LIA_Claimant AS (

  SELECT 
    in1.Claim_Loss_Date_Modified_User_Key AS Claim_Loss_Date_Modified_User_Key,
    in1.Claim_WC_Department_Name AS Claim_WC_Department_Name,
    in1.Claim_Notified_Date_Key AS Claim_Notified_Date_Key,
    in1.Claim_WC_Injury_Object_Involved_Name AS Claim_WC_Injury_Object_Involved_Name,
    in1.Claim_WC_Worker_Postcode AS Claim_WC_Worker_Postcode,
    in1.Claim_WC_Medical_Certificate_Last_Date_Key AS Claim_WC_Medical_Certificate_Last_Date_Key,
    in1.Claim_Duplicate_Loss_Days_Tolerance_Key AS Claim_Duplicate_Loss_Days_Tolerance_Key,
    in1.Claim_Reopened_YN AS Claim_Reopened_YN,
    in1.Claim_Liability_Other_Damages_YN AS Claim_Liability_Other_Damages_YN,
    in1.Claim_Solicitor_Key AS Claim_Solicitor_Key,
    in1.Claim_Indemnity_Decision_Key AS Claim_Indemnity_Decision_Key,
    in1.Claim_Reported_Date_Key AS Claim_Reported_Date_Key,
    in1.Claim_Liability_Litigation_Status_Code AS Claim_Liability_Litigation_Status_Code,
    in1.Claim_WC_Loss_Time_Number AS Claim_WC_Loss_Time_Number,
    in1.Claim_Key AS Claim_Key,
    in1.Company_Key AS Company_Key,
    in1.Claim_WC_IMA_Date_Key AS Claim_WC_IMA_Date_Key,
    in1.Claim_WC_Breakdown_Agency_Key AS Claim_WC_Breakdown_Agency_Key,
    in1.Claim_Motor_Vehicle_Usage_Code AS Claim_Motor_Vehicle_Usage_Code,
    in1.Claim_WC_Classification_Code AS Claim_WC_Classification_Code,
    in1.Claim_Key1 AS Claim_Key1,
    in1.Claim_Indemnity_Decision_Date_Key AS Claim_Indemnity_Decision_Date_Key,
    in1.Claim_Motor_Fault_Key AS Claim_Motor_Fault_Key,
    in1.Claim_Liability_Cause_Code AS Claim_Liability_Cause_Code,
    in1.Claim_Cause_of_Loss_Description AS Claim_Cause_of_Loss_Description,
    in1.Claim_Liability_Law_Costs_YN AS Claim_Liability_Law_Costs_YN,
    in1.Claim_Updated_User_Key AS Claim_Updated_User_Key,
    in1.Claim_Loss_Date_Modified_Date_Key AS Claim_Loss_Date_Modified_Date_Key,
    in1.Risk_Class_Key AS Risk_Class_Key,
    in1.Claim_Number AS Claim_Number,
    in1.Claim_WC_Gender_Code AS Claim_WC_Gender_Code,
    in1.Claim_Motor_Vehicle_Class_Key AS Claim_Motor_Vehicle_Class_Key,
    in1.Claim_Postcode AS Claim_Postcode,
    in1.Claim_WC_Injury_Mechanism_Key AS Claim_WC_Injury_Mechanism_Key,
    in1.Claim_Recovery_Changed_Date_Key AS Claim_Recovery_Changed_Date_Key,
    in1.Claim_Loss_Location_Key AS Claim_Loss_Location_Key,
    in1.ASCO_Key AS ASCO_Key,
    in1.Claim_WC_Fitness_Level_Code AS Claim_WC_Fitness_Level_Code,
    in1.Industry_Class_ANZSIC_93_Key AS Industry_Class_ANZSIC_93_Key,
    in1.Claim_WC_Injury_Nature_Key AS Claim_WC_Injury_Nature_Key,
    in1.Claim_Duplicate_Status_Key AS Claim_Duplicate_Status_Key,
    in1.Claim_Liability_Property_Damage_YN AS Claim_Liability_Property_Damage_YN,
    in1.Claim_Loss_Date_Difference_Days_Number AS Claim_Loss_Date_Difference_Days_Number,
    in1.Claim_Date_Accepted_Key AS Claim_Date_Accepted_Key,
    in1.Claim_Liability_Date_Key AS Claim_Liability_Date_Key,
    in1.Claim_Liability_Personal_Injury_YN AS Claim_Liability_Personal_Injury_YN,
    in1.Catastrophe_Event_ICA_Key AS Catastrophe_Event_ICA_Key,
    in1.Claim_WC_Common_Law_Outcome_Code AS Claim_WC_Common_Law_Outcome_Code,
    in1.Claim_WC_Worker_Weekly_Hours_Time AS Claim_WC_Worker_Weekly_Hours_Time,
    in1.Claim_WC_Received_Date_by_Employer AS Claim_WC_Received_Date_by_Employer,
    in1.Claim_Motor_Vehicle_Manufactured_Year_Number AS Claim_Motor_Vehicle_Manufactured_Year_Number,
    in1.Broker_Account_Key AS Broker_Account_Key,
    in1.Claim_WC_Work_Resumed_Date_Key AS Claim_WC_Work_Resumed_Date_Key,
    in1.Claim_WC_Occupation_Name AS Claim_WC_Occupation_Name,
    in0.Claimant_Name AS Claimant_Name,
    in1.Claim_Updated_Date_Key AS Claim_Updated_Date_Key,
    in1.Policy_Key AS Policy_Key,
    in1.Claim_Type_Key AS Claim_Type_Key,
    in1.Claim_Liability_Severity_Code AS Claim_Liability_Severity_Code,
    in1.Claim_Motor_Cost_Centre_Name AS Claim_Motor_Cost_Centre_Name,
    in1.Premium_Class_Key AS Premium_Class_Key,
    in1.Claim_Agg_Arrangement_Key AS Claim_Agg_Arrangement_Key,
    in1.ARPC_Incident_Number AS ARPC_Incident_Number,
    in1.Claim_Motor_Driver_Gender_Code AS Claim_Motor_Driver_Gender_Code,
    in1.Claim_Liability_Status_Code AS Claim_Liability_Status_Code,
    in1.Claim_Recovery_YN AS Claim_Recovery_YN,
    in1.Product_Key AS Product_Key,
    in1.Claim_Salvage_YN AS Claim_Salvage_YN,
    in1.Claim_Duplicate_Loss_Days_Number AS Claim_Duplicate_Loss_Days_Number,
    in1.Claim_Duplicate_Potential_YN AS Claim_Duplicate_Potential_YN,
    in1.Claim_WC_Injury_Most_Serious_Description AS Claim_WC_Injury_Most_Serious_Description,
    in1.Claim_Liability_Financial_Loss_YN AS Claim_Liability_Financial_Loss_YN,
    in1.Industry_Class_ANZSIC_2006_Key AS Industry_Class_ANZSIC_2006_Key,
    in1.Risk_Key AS Risk_Key,
    in1.Claim_Investigator_Key AS Claim_Investigator_Key,
    in1.Claim_Agg_Arrangement_Type_Key AS Claim_Agg_Arrangement_Type_Key,
    in1.Claim_Motor_Vehicle_Description AS Claim_Motor_Vehicle_Description,
    in1.Claim_WC_Marital_Status_Code AS Claim_WC_Marital_Status_Code,
    in1.Claim_WC_Worker_Name AS Claim_WC_Worker_Name,
    in1.Claim_Duty_Status AS Claim_Duty_Status,
    in1.Claim_WC_Worker_Weekly_Hours_Rate AS Claim_WC_Worker_Weekly_Hours_Rate,
    in1.Claim_Branch_Key AS Claim_Branch_Key,
    in1.Claim_WC_Hourly_Rate_Thereafter_Amount AS Claim_WC_Hourly_Rate_Thereafter_Amount,
    in1.Claim_Fraud_Type_Key AS Claim_Fraud_Type_Key,
    in1.Claim_Motor_Vehicle_Rego_Code AS Claim_Motor_Vehicle_Rego_Code,
    in1.Claim_Portfolio_Key AS Claim_Portfolio_Key,
    in1.Claim_Motor_Bodily_Injury_YN AS Claim_Motor_Bodily_Injury_YN,
    in1.Claim_Loss_Date_Modified_YN AS Claim_Loss_Date_Modified_YN,
    in1.Claim_WC_Lost_Minutes_Number AS Claim_WC_Lost_Minutes_Number,
    in1.Claim_Gross_Incurred_Loss_Type_Key AS Claim_Gross_Incurred_Loss_Type_Key,
    in1.Claim_WC_Lost_Hours_Number AS Claim_WC_Lost_Hours_Number,
    in1.Client_Claim_Number AS Client_Claim_Number,
    in1.Claim_WC_Work_Status AS Claim_WC_Work_Status,
    in1.Claim_WC_Estimated_Return_Date_Key AS Claim_WC_Estimated_Return_Date_Key,
    in1.Global_LoB_Key AS Global_LoB_Key,
    in1.Policy_Period_Name AS Policy_Period_Name,
    in1.Claim_Recovery_Abandonment_Reason_Key AS Claim_Recovery_Abandonment_Reason_Key,
    in1.Claim_Handler_Key AS Claim_Handler_Key,
    in1.Claim_Updated_Datetime AS Claim_Updated_Datetime,
    in0.Claim_Motor_Driver_Name AS Claim_Motor_Driver_Name,
    in1.Claim_BGC_Status_Code AS Claim_BGC_Status_Code,
    in1.Claim_WC_Common_Law_Raised_Date_Key AS Claim_WC_Common_Law_Raised_Date_Key,
    in1.Claim_Reopened_Last_Date_Key AS Claim_Reopened_Last_Date_Key,
    in1.Client_Key AS Client_Key,
    in1.Claim_Date_Rejected_Key AS Claim_Date_Rejected_Key,
    in1.Claim_WC_Full_Time_Part_Time_Code AS Claim_WC_Full_Time_Part_Time_Code,
    in1.Claim_WC_Worker_State_Code AS Claim_WC_Worker_State_Code,
    in1.Claim_Motor_Vehicle_Finance_YN AS Claim_Motor_Vehicle_Finance_YN,
    in1.Claim_WC_Worker_Suburb_Name AS Claim_WC_Worker_Suburb_Name,
    in1.Claim_Motor_Vehicle_Loss_Day_of_Week_Code AS Claim_Motor_Vehicle_Loss_Day_of_Week_Code,
    in1.Claim_Cyclone_Flag AS Claim_Cyclone_Flag,
    in1.Claim_UX_Type_Code AS Claim_UX_Type_Code,
    in1.Claim_Motor_Driver_Licensed_Years_Number AS Claim_Motor_Driver_Licensed_Years_Number,
    in1.Claim_Division_Name AS Claim_Division_Name,
    in0.Claim_Motor_Driver_Names_Text AS Claim_Motor_Driver_Names_Text,
    in1.Claim_Expiry_Date_Key AS Claim_Expiry_Date_Key,
    in1.Claim_Status_Key AS Claim_Status_Key,
    in1.Claim_Time_Occurence AS Claim_Time_Occurence,
    in1.Claim_WC_IMA_Reviewed_YN AS Claim_WC_IMA_Reviewed_YN,
    in1.Claim_WC_Worker_RTW_Program AS Claim_WC_Worker_RTW_Program,
    in1.Claim_Loss_Date_Key AS Claim_Loss_Date_Key,
    in1.Claim_Closed_Date_Key AS Claim_Closed_Date_Key,
    in1.Claim_WC_Birth_Date_Key AS Claim_WC_Birth_Date_Key,
    in1.Claim_WC_Hourly_Rate_First_13_Weeks_Amount AS Claim_WC_Hourly_Rate_First_13_Weeks_Amount,
    in0.Claim_Key2 AS Claim_Key2,
    in1.Claim_Non_Standard_Type_Key AS Claim_Non_Standard_Type_Key,
    in1.Claim_Motor_Vehicle_Total_Loss_YN AS Claim_Motor_Vehicle_Total_Loss_YN,
    in1.Claim_WC_Ceased_Work_Date_Key AS Claim_WC_Ceased_Work_Date_Key,
    in1.Claim_WC_Common_Law_Severity_Code AS Claim_WC_Common_Law_Severity_Code,
    in1.Claim_WC_Agency_of_Accident_Key AS Claim_WC_Agency_of_Accident_Key,
    in1.Claim_WC_Worker_RTW_Goals AS Claim_WC_Worker_RTW_Goals,
    in1.Claim_Loss_Orig_Date_Key AS Claim_Loss_Orig_Date_Key,
    in1.Policy_Incep_Date_Key AS Policy_Incep_Date_Key,
    in1.Claim_Duplicate_Potential_Key AS Claim_Duplicate_Potential_Key,
    in1.Claim_Motor_Vehicle_Loss_Time_Number AS Claim_Motor_Vehicle_Loss_Time_Number,
    in1.Claim_vulnerable_flag AS Claim_vulnerable_flag,
    in1.Claim_Status_Date_Key AS Claim_Status_Date_Key,
    in1.Claim_Motor_Driver_Age_Years_Number AS Claim_Motor_Driver_Age_Years_Number,
    in1.Claim_WC_Loss_Day_of_Week_Code AS Claim_WC_Loss_Day_of_Week_Code,
    in1.Claim_WC_Body_Location_Key AS Claim_WC_Body_Location_Key,
    in1.Claim_State_Code AS Claim_State_Code,
    in1.Claim_Recovery_Changed_YN AS Claim_Recovery_Changed_YN,
    in1.Claim_Assessor_Key AS Claim_Assessor_Key,
    in1.Claim_UX_Arrangement_Description AS Claim_UX_Arrangement_Description
  
  FROM Srt_Claimant_EXPR_357 AS in0
  INNER JOIN Jnr_Claim_CA_WC_LIA AS in1
     ON (in0.Claim_Key2 = in1.Claim_Key)

),

EXP_DATATYPE_CONVERSION1 AS (

  SELECT 
    Claim_Key AS Claim_Key,
    Claim_Number AS Claim_Number,
    Claimant_Name AS Claimant_Name,
    Claim_Cause_of_Loss_Description AS Claim_Cause_of_Loss_Description,
    Claim_Postcode AS Claim_Postcode,
    Claim_UX_Type_Code AS Claim_UX_Type_Code,
    Claim_UX_Arrangement_Description AS Claim_UX_Arrangement_Description,
    Claim_Salvage_YN AS Claim_Salvage_YN,
    Claim_Recovery_YN AS Claim_Recovery_YN,
    Claim_Liability_Personal_Injury_YN AS Claim_Liability_Personal_Injury_YN,
    Company_Key AS Company_Key,
    Claim_Branch_Key AS Claim_Branch_Key,
    Premium_Class_Key AS Premium_Class_Key,
    Product_Key AS Product_Key,
    Global_LoB_Key AS Global_LoB_Key,
    Claim_Reported_Date_Key AS Claim_Reported_Date_Key,
    Claim_Expiry_Date_Key AS Claim_Expiry_Date_Key,
    Claim_Loss_Date_Key AS Claim_Loss_Date_Key,
    Claim_Indemnity_Decision_Key AS Claim_Indemnity_Decision_Key,
    Claim_Indemnity_Decision_Date_Key AS Claim_Indemnity_Decision_Date_Key,
    Claim_Status_Date_Key AS Claim_Status_Date_Key,
    Claim_Solicitor_Key AS Claim_Solicitor_Key,
    Claim_Assessor_Key AS Claim_Assessor_Key,
    Claim_Investigator_Key AS Claim_Investigator_Key,
    Catastrophe_Event_ICA_Key AS Catastrophe_Event_ICA_Key,
    Claim_Handler_Key AS Claim_Handler_Key,
    Policy_Key AS Policy_Key,
    Claim_Portfolio_Key AS Claim_Portfolio_Key,
    Risk_Key AS Risk_Key,
    Claim_Reopened_YN AS Claim_Reopened_YN,
    Claim_Notified_Date_Key AS Claim_Notified_Date_Key,
    Claim_State_Code AS Claim_State_Code,
    Claim_Type_Key AS Claim_Type_Key,
    Claim_Status_Key AS Claim_Status_Key,
    Risk_Class_Key AS Risk_Class_Key,
    Broker_Account_Key AS Broker_Account_Key,
    Client_Key AS Client_Key,
    Policy_Incep_Date_Key AS Policy_Incep_Date_Key,
    Policy_Period_Name AS Policy_Period_Name,
    Claim_Closed_Date_Key AS Claim_Closed_Date_Key,
    Claim_Non_Standard_Type_Key AS Claim_Non_Standard_Type_Key,
    Claim_Reopened_Last_Date_Key AS Claim_Reopened_Last_Date_Key,
    Claim_Date_Accepted_Key AS Claim_Date_Accepted_Key,
    Claim_Date_Rejected_Key AS Claim_Date_Rejected_Key,
    Claim_Division_Name AS Claim_Division_Name,
    CAST(Claim_Motor_Fault_Key AS string) AS Claim_Motor_Fault_Key,
    Claim_Motor_Vehicle_Class_Key AS Claim_Motor_Vehicle_Class_Key,
    Claim_Motor_Bodily_Injury_YN AS Claim_Motor_Bodily_Injury_YN,
    Claim_Motor_Vehicle_Loss_Day_of_Week_Code AS Claim_Motor_Vehicle_Loss_Day_of_Week_Code,
    Claim_Motor_Vehicle_Loss_Time_Number AS Claim_Motor_Vehicle_Loss_Time_Number,
    Claim_Motor_Cost_Centre_Name AS Claim_Motor_Cost_Centre_Name,
    CAST(Claim_Motor_Driver_Age_Years_Number AS string) AS Claim_Motor_Driver_Age_Years_Number,
    Claim_Motor_Vehicle_Finance_YN AS Claim_Motor_Vehicle_Finance_YN,
    Claim_Motor_Vehicle_Rego_Code AS Claim_Motor_Vehicle_Rego_Code,
    Claim_Motor_Vehicle_Total_Loss_YN AS Claim_Motor_Vehicle_Total_Loss_YN,
    Claim_Motor_Vehicle_Description AS Claim_Motor_Vehicle_Description,
    Claim_Motor_Vehicle_Usage_Code AS Claim_Motor_Vehicle_Usage_Code,
    CAST(Claim_Motor_Driver_Licensed_Years_Number AS string) AS Claim_Motor_Driver_Licensed_Years_Number,
    CAST(Claim_Motor_Vehicle_Manufactured_Year_Number AS string) AS Claim_Motor_Vehicle_Manufactured_Year_Number,
    Claim_Motor_Driver_Gender_Code AS Claim_Motor_Driver_Gender_Code,
    Claim_Motor_Driver_Name AS Claim_Motor_Driver_Name,
    Claim_WC_Worker_Suburb_Name AS Claim_WC_Worker_Suburb_Name,
    Claim_WC_Worker_State_Code AS Claim_WC_Worker_State_Code,
    Claim_WC_Worker_Postcode AS Claim_WC_Worker_Postcode,
    Claim_WC_Gender_Code AS Claim_WC_Gender_Code,
    Claim_WC_Birth_Date_Key AS Claim_WC_Birth_Date_Key,
    Claim_WC_Marital_Status_Code AS Claim_WC_Marital_Status_Code,
    Claim_WC_Full_Time_Part_Time_Code AS Claim_WC_Full_Time_Part_Time_Code,
    Claim_WC_Hourly_Rate_First_13_Weeks_Amount AS Claim_WC_Hourly_Rate_First_13_Weeks_Amount,
    Claim_WC_Hourly_Rate_Thereafter_Amount AS Claim_WC_Hourly_Rate_Thereafter_Amount,
    Claim_WC_Worker_Weekly_Hours_Rate AS Claim_WC_Worker_Weekly_Hours_Rate,
    Claim_WC_Worker_Weekly_Hours_Time AS Claim_WC_Worker_Weekly_Hours_Time,
    Claim_WC_Occupation_Name AS Claim_WC_Occupation_Name,
    Claim_WC_Classification_Code AS Claim_WC_Classification_Code,
    CAST(Claim_WC_Body_Location_Key AS string) AS Claim_WC_Body_Location_Key,
    CAST(Claim_WC_Agency_of_Accident_Key AS string) AS Claim_WC_Agency_of_Accident_Key,
    CAST(Claim_WC_Breakdown_Agency_Key AS string) AS Claim_WC_Breakdown_Agency_Key,
    Claim_WC_Ceased_Work_Date_Key AS Claim_WC_Ceased_Work_Date_Key,
    Claim_WC_Common_Law_Raised_Date_Key AS Claim_WC_Common_Law_Raised_Date_Key,
    Claim_WC_Common_Law_Outcome_Code AS Claim_WC_Common_Law_Outcome_Code,
    Claim_WC_Common_Law_Severity_Code AS Claim_WC_Common_Law_Severity_Code,
    Claim_WC_Medical_Certificate_Last_Date_Key AS Claim_WC_Medical_Certificate_Last_Date_Key,
    Claim_WC_Loss_Day_of_Week_Code AS Claim_WC_Loss_Day_of_Week_Code,
    Claim_WC_Estimated_Return_Date_Key AS Claim_WC_Estimated_Return_Date_Key,
    Claim_WC_IMA_Date_Key AS Claim_WC_IMA_Date_Key,
    Claim_WC_IMA_Reviewed_YN AS Claim_WC_IMA_Reviewed_YN,
    Claim_WC_Injury_Mechanism_Key AS Claim_WC_Injury_Mechanism_Key,
    Claim_WC_Injury_Nature_Key AS Claim_WC_Injury_Nature_Key,
    Claim_WC_Fitness_Level_Code AS Claim_WC_Fitness_Level_Code,
    Claim_WC_Lost_Hours_Number AS Claim_WC_Lost_Hours_Number,
    Claim_WC_Lost_Minutes_Number AS Claim_WC_Lost_Minutes_Number,
    Claim_WC_Injury_Most_Serious_Description AS Claim_WC_Injury_Most_Serious_Description,
    Claim_WC_Injury_Object_Involved_Name AS Claim_WC_Injury_Object_Involved_Name,
    Claim_WC_Work_Resumed_Date_Key AS Claim_WC_Work_Resumed_Date_Key,
    Claim_WC_Loss_Time_Number AS Claim_WC_Loss_Time_Number,
    Claim_WC_Department_Name AS Claim_WC_Department_Name,
    Claim_WC_Worker_Name AS Claim_WC_Worker_Name,
    ASCO_Key AS ASCO_Key,
    Industry_Class_ANZSIC_93_Key AS Industry_Class_ANZSIC_93_Key,
    Industry_Class_ANZSIC_2006_Key AS Industry_Class_ANZSIC_2006_Key,
    Claim_Liability_Status_Code AS Claim_Liability_Status_Code,
    Claim_Liability_Law_Costs_YN AS Claim_Liability_Law_Costs_YN,
    Claim_Liability_Other_Damages_YN AS Claim_Liability_Other_Damages_YN,
    Claim_Liability_Cause_Code AS Claim_Liability_Cause_Code,
    Claim_Liability_Severity_Code AS Claim_Liability_Severity_Code,
    Claim_Liability_Litigation_Status_Code AS Claim_Liability_Litigation_Status_Code,
    Claim_Liability_Date_Key AS Claim_Liability_Date_Key,
    Claim_Liability_Property_Damage_YN AS Claim_Liability_Property_Damage_YN,
    Claim_Liability_Financial_Loss_YN AS Claim_Liability_Financial_Loss_YN,
    Claim_Agg_Arrangement_Type_Key AS Claim_Agg_Arrangement_Type_Key,
    Claim_Agg_Arrangement_Key AS Claim_Agg_Arrangement_Key,
    Claim_Loss_Location_Key AS Claim_Loss_Location_Key,
    Claim_BGC_Status_Code AS Claim_BGC_Status_Code,
    Claim_Loss_Date_Difference_Days_Number AS Claim_Loss_Date_Difference_Days_Number,
    Claim_Loss_Date_Modified_Date_Key AS Claim_Loss_Date_Modified_Date_Key,
    Claim_Loss_Date_Modified_User_Key AS Claim_Loss_Date_Modified_User_Key,
    Claim_Loss_Date_Modified_YN AS Claim_Loss_Date_Modified_YN,
    Claim_Loss_Orig_Date_Key AS Claim_Loss_Orig_Date_Key,
    Claim_Motor_Driver_Names_Text AS Claim_Motor_Driver_Names_Text,
    Claim_Recovery_Abandonment_Reason_Key AS Claim_Recovery_Abandonment_Reason_Key,
    Claim_Recovery_Changed_YN AS Claim_Recovery_Changed_YN,
    Claim_Recovery_Changed_Date_Key AS Claim_Recovery_Changed_Date_Key,
    Claim_Updated_Datetime AS Claim_Updated_Datetime,
    Claim_Updated_Date_Key AS Claim_Updated_Date_Key,
    Claim_Updated_User_Key AS Claim_Updated_User_Key,
    Claim_Duplicate_Status_Key AS Claim_Duplicate_Status_Key,
    Claim_Fraud_Type_Key AS Claim_Fraud_Type_Key,
    Claim_Duplicate_Loss_Days_Tolerance_Key AS Claim_Duplicate_Loss_Days_Tolerance_Key,
    Claim_Duplicate_Loss_Days_Number AS Claim_Duplicate_Loss_Days_Number,
    Claim_Duplicate_Potential_YN AS Claim_Duplicate_Potential_YN,
    Claim_Duplicate_Potential_Key AS Claim_Duplicate_Potential_Key,
    Claim_Gross_Incurred_Loss_Type_Key AS Claim_Gross_Incurred_Loss_Type_Key,
    Client_Claim_Number AS Client_Claim_Number,
    Claim_WC_Received_Date_by_Employer AS Claim_WC_Received_Date_by_Employer,
    Claim_WC_Work_Status AS Claim_WC_Work_Status,
    Claim_WC_Worker_RTW_Program AS Claim_WC_Worker_RTW_Program,
    Claim_WC_Worker_RTW_Goals AS Claim_WC_Worker_RTW_Goals,
    Claim_Duty_Status AS Claim_Duty_Status,
    Claim_vulnerable_flag AS Claim_Vulnerable_Flag,
    Claim_Time_Occurence AS Claim_Time_Occurence,
    Claim_Cyclone_Flag AS Claim_Cyclone_Flag,
    ARPC_Incident_Number AS ARPC_Incident_Number
  
  FROM Jnr_Claim_CA_WC_LIA_Claimant AS in0

)

SELECT *

FROM EXP_DATATYPE_CONVERSION1
