{{
  config({    
    "materialized": "table",
    "alias": "sh_DATA_GI_CLAIM_BAL_MTH_AGG",
    "database": "qa_team",
    "schema": "qa_orchestration"
  })
}}

WITH `35_SDMmp_sdm_sdm_Data_GI_Claim_Bal_Mth_Agg_sh_DATA_GI_CLAIM_MOVEMENT` AS (

  SELECT *
  
  FROM {{
    prophecy_tmp_source(
      '35_SDM_mp_sdm_sdm_Data_GI_Claim_Bal_Mth_Agg', 
      '35_SDMmp_sdm_sdm_Data_GI_Claim_Bal_Mth_Agg_sh_DATA_GI_CLAIM_MOVEMENT'
    )
  }}

),

EXP_Cal_Cummulative_Bal_Mth AS (

  SELECT 
    CLAIM_ID AS CLAIM_ID,
    PRD_ID AS PRD_ID,
    RSK_CLASS_ID AS RSK_CLASS_ID,
    PREM_CLASS_ID AS PREM_CLASS_ID,
    CLAIM_PAYMT_TYPE_ID AS CLAIM_PAYMT_TYPE_ID,
    MTRN_TYPE_CODE AS MTRN_TYPE_CODE,
    ACCTING_MTH_ID AS ACCT_MTH_ID,
    POLICY_ID AS POLICY_ID,
    POL_BRANCH_ID AS POL_BRANCH_ID,
    TRANS_CCY_CODE AS CCY_CODE,
    APC_AMT_SUM AS APC_AMT,
    GOL_AMT_SUM AS GOL_AMT,
    GPC_AMT_SUM AS GPC_AMT,
    RPC_AMT_SUM AS RPC_AMT,
    ROL_AMT_SUM AS ROL_AMT,
    AOL_AMT_SUM AS AOL_AMT,
    SPC_AMT_SUM AS SPC_AMT,
    SOL_AMT_SUM AS SOL_AMT,
    TPC_AMT_SUM AS TPC_AMT,
    TOL_AMT_SUM AS TOL_AMT,
    UPC_AMT_SUM AS UPC_AMT,
    UOL_AMT_SUM AS UOL_AMT,
    CLAIM_OWNR_CODE AS CLAIM_OWNR_CODE,
    CLAIM_SEGMENT_ID AS CLAIM_SEGMENT_ID,
    CLAIM_SUBSEG_ID AS CLAIM_SUBSEG_ID,
    CLAIM_CATASTROPHE_CODE AS CLAIM_CATASTROPHE_CODE,
    INTERMEDIARY_ID AS INTERMEDIARY_ID,
    CLIENT_ID AS CLIENT_ID,
    ASSESSOR_ID AS ASSESSOR_ID,
    LOSS_DATE_ID AS LOSS_DATE_ID,
    CLAIM_OFFICER_PARTY_NUM AS CLAIM_OFFICER_PARTY_NUM,
    BODILY_INJURY_CODE AS BODILY_INJURY_CODE,
    CLAIM_OFFICER_PARTY_ID AS CLAIM_OFFICER_PARTY_ID,
    UNDER_EXCESS_TYPE AS UNDER_EXCESS_TYPE,
    MARKET_SEGMENT_ID AS MARKET_SEGMENT_ID,
    ACDNT_MTH_ID AS ACDNT_MTH_ID,
    RPTED_MTH_ID AS RPTED_MTH_ID,
    RPTED_DATE_ID AS RPTED_DATE_ID
  
  FROM `35_SDMmp_sdm_sdm_Data_GI_Claim_Bal_Mth_Agg_sh_DATA_GI_CLAIM_MOVEMENT` AS in0

),

EXP_Calculate_End_Acct_Mth_Id AS (

  SELECT 
    CLAIM_ID AS CLAIM_ID,
    PRD_ID AS PRD_ID,
    RSK_CLASS_ID AS RSK_CLASS_ID,
    PREM_CLASS_ID AS PREM_CLASS_ID,
    CLAIM_PAYMT_TYPE_ID AS CLAIM_PAYMT_TYPE_ID,
    MTRN_TYPE_CODE AS MTRN_TYPE_CODE,
    ACCT_MTH_ID AS ACCT_MTH_ID,
    POLICY_ID AS POLICY_ID,
    POL_BRANCH_ID AS POL_BRANCH_ID,
    CCY_CODE AS CCY_CODE,
    APC_AMT AS APC_AMT,
    GOL_AMT AS GOL_AMT,
    GPC_AMT AS GPC_AMT,
    RPC_AMT AS RPC_AMT,
    ROL_AMT AS ROL_AMT,
    AOL_AMT AS AOL_AMT,
    SPC_AMT AS SPC_AMT,
    SOL_AMT AS SOL_AMT,
    TPC_AMT AS TPC_AMT,
    TOL_AMT AS TOL_AMT,
    UPC_AMT AS UPC_AMT,
    UOL_AMT AS UOL_AMT,
    CLAIM_OWNR_CODE AS CLAIM_OWNR_CODE,
    CLAIM_SEGMENT_ID AS CLAIM_SEGMENT_ID,
    CLAIM_SUBSEG_ID AS CLAIM_SUBSEG_ID,
    CLAIM_CATASTROPHE_CODE AS CLAIM_CATASTROPHE_CODE,
    INTERMEDIARY_ID AS INTERMEDIARY_ID,
    CLIENT_ID AS CLIENT_ID,
    ASSESSOR_ID AS ASSESSOR_ID,
    LOSS_DATE_ID AS LOSS_DATE_ID,
    CLAIM_OFFICER_PARTY_NUM AS CLAIM_OFFICER_PARTY_NUM,
    BODILY_INJURY_CODE AS BODILY_INJURY_CODE,
    CLAIM_OFFICER_PARTY_ID AS CLAIM_OFFICER_PARTY_ID,
    UNDER_EXCESS_TYPE AS UNDER_EXCESS_TYPE,
    MARKET_SEGMENT_ID AS MARKET_SEGMENT_ID,
    ACDNT_MTH_ID AS ACDNT_MTH_ID,
    RPTED_MTH_ID AS RPTED_MTH_ID,
    RPTED_DATE_ID AS RPTED_DATE_ID,
    (
      CASE
        WHEN (
          (
            (
              (
                (
                  (
                    ((LAG(CLAIM_ID) OVER (PARTITION BY 1 ORDER BY 1 NULLS FIRST)) = CLAIM_ID)
                    AND ((LAG(PRD_ID) OVER (PARTITION BY 1 ORDER BY 1 NULLS FIRST)) = PRD_ID)
                  )
                  AND ((LAG(RSK_CLASS_ID) OVER (PARTITION BY 1 ORDER BY 1 NULLS FIRST)) = RSK_CLASS_ID)
                )
                AND ((LAG(PREM_CLASS_ID) OVER (PARTITION BY 1 ORDER BY 1 NULLS FIRST)) = PREM_CLASS_ID)
              )
              AND ((LAG(CLAIM_PAYMT_TYPE_ID) OVER (PARTITION BY 1 ORDER BY 1 NULLS FIRST)) = CLAIM_PAYMT_TYPE_ID)
            )
            AND ((LAG(MTRN_TYPE_CODE) OVER (PARTITION BY 1 ORDER BY 1 NULLS FIRST)) = MTRN_TYPE_CODE)
          )
          AND ((LAG(ACCT_MTH_ID) OVER (PARTITION BY 1 ORDER BY 1 NULLS FIRST)) <> ACCT_MTH_ID)
        )
          THEN (
            CASE
              WHEN (CAST(SUBSTRING(CAST((LAG(ACCT_MTH_ID) OVER (PARTITION BY 1 ORDER BY 1 NULLS FIRST)) AS string), 5, 2) AS string) = '01')
                THEN (
                  (
                    (
                      CAST(SUBSTRING(CAST((LAG(ACCT_MTH_ID) OVER (PARTITION BY 1 ORDER BY 1 NULLS FIRST)) AS string), 1, 4) AS INTEGER)
                      - 1
                    )
                    * 100
                  )
                  + 12
                )
              ELSE ((LAG(ACCT_MTH_ID) OVER (PARTITION BY 1 ORDER BY 1 NULLS FIRST)) - 1)
            END
          )
        ELSE 999912
      END
    ) AS END_ACCT_MTH_ID,
    {{ var('PMWorkflowRunId') }} AS CTL_JOB_ID,
    CURRENT_TIMESTAMP AS CTL_REC_CRTN_DATE,
    '-' AS TAKEUP_RANK
  
  FROM EXP_Cal_Cummulative_Bal_Mth AS in0

)

SELECT *

FROM EXP_Calculate_End_Acct_Mth_Id
