{{
  config({    
    "materialized": "table",
    "alias": "AUDIT_TASK_RUN",
    "database": "qa_team",
    "schema": "qa_orchestration"
  })
}}

WITH EXPTRANS1 AS (

  SELECT *
  
  FROM {{ ref('15_RDV_POL_mp_log_audit_info_1__EXPTRANS1')}}

),

AUDIT_TASK_RUN_EXP AS (

  SELECT 
    SUBJECT_AREA AS SUBJECT_AREA,
    JOB_ID AS JOB_ID,
    JOB_NAME AS JOB_NAME,
    TASK_ID AS TASK_ID,
    TASK_NAME AS TASK_NAME,
    TARGET_OBJECT_NAME AS TARGET_OBJECT_NAME,
    JOB_RUN_ID AS JOB_RUN_ID,
    SOURCE_AFFECTED_ROWS AS SOURCE_AFFECTED_ROWS,
    SOURCE_REJECTED_ROWS AS SOURCE_REJECTED_ROWS,
    SOURCE_FILTERED_ROWS AS SOURCE_FILTERED_ROWS,
    TARGET_AFFECTED_ROWS AS TARGET_AFFECTED_ROWS,
    TARGET_REJECTED_ROWS AS TARGET_REJECTED_ROWS,
    TARGET_FILTERED_ROWS AS TARGET_FILTERED_ROWS,
    task_start_time AS task_start_time,
    task_end_time AS task_end_time,
    Throughput AS Throughput,
    error_msg AS error_msg,
    EXECUTED_QUERY AS EXECUTED_QUERY,
    EXECUTED_QUERY_ERROR_LOG AS EXECUTED_QUERY_ERROR_LOG,
    CTL_BATCH_ID AS CTL_BATCH_ID,
    CTL_INTRADAY_ID AS CTL_INTRADAY_ID,
    CTL_JOB_RUN_ID AS CTL_JOB_RUN_ID,
    CTL_REC_CRTN_DATE AS CTL_REC_CRTN_DATE
  
  FROM EXPTRANS1 AS in0

)

SELECT *

FROM AUDIT_TASK_RUN_EXP
