{{
  config({    
    "materialized": "table",
    "alias": "DNM_AUTH_AU_NZ_MYAUTHORITY_ALLUSERS_DELTA",
    "database": "qa_team",
    "schema": "qa_orchestration"
  })
}}

WITH `30_MDL_AUTHORITIESmp_myauthorities_stg_mdl_dnm_AU_NZ_MyAuthority_Delta_SRC_AUTH_AU_NZ_MYAUTHORITY_ALLUSERS_DELTA` AS (

  SELECT *
  
  FROM {{
    prophecy_tmp_source(
      '30_MDL_AUTHORITIES_mp_myauthorities_stg_mdl_dnm_AU_NZ_MyAuthority_Delta', 
      '30_MDL_AUTHORITIESmp_myauthorities_stg_mdl_dnm_AU_NZ_MyAuthority_Delta_SRC_AUTH_AU_NZ_MYAUTHORITY_ALLUSERS_DELTA'
    )
  }}

),

EXP_INIT AS (

  SELECT 
    USERID AS USERID,
    EMAILID AS EMAILID,
    USERNAME AS USERNAME,
    REGIONNAME AS REGIONNAME,
    COUNTRYNAME AS COUNTRYNAME,
    MYAUTHORITYCOUNTRY AS MYAUTHORITYCOUNTRY,
    ZURICHORG AS ZURICHORG,
    USERTYPE AS USERTYPE,
    USERROLE AS USERROLE,
    MANAGER AS MANAGER,
    DEPARTMENT AS DEPARTMENT,
    TITLE AS TITLE,
    ORGANIZATIONS AS ORGANIZATIONS,
    ALLOWGRANTANDSIGNLOA AS ALLOWGRANTANDSIGNLOA,
    STATUS AS STATUS,
    STATUSLOG_UPDATEDDATE AS STATUSLOG_UPDATEDDATE,
    LOAEFFECTIVEDATE AS LOAEFFECTIVEDATE,
    ACTION AS ACTION,
    INACTIVE AS INACTIVE,
    ISREISSUED AS ISREISSUED,
    INREISSUEDFLOW AS INREISSUEDFLOW,
    OLDLOAEFFECTIVEDATE AS OLDLOAEFFECTIVEDATE,
    LOATERMINATEDEFFECTIVEDATE AS LOATERMINATEDEFFECTIVEDATE,
    ALLVALUESIN AS ALLVALUESIN,
    LOBLIMITS_AUTOCONVERT AS LOBLIMITS_AUTOCONVERT,
    HIDEUSD AS HIDEUSD,
    ISBEHALFOFGRANTORSSIGNATORIES AS ISBEHALFOFGRANTORSSIGNATORIES,
    ACTIVEGRANTOR_EMAILID AS ACTIVEGRANTOR_EMAILID,
    SELECTEDGRANTORFORLOA_MAILID AS SELECTEDGRANTORFORLOA_MAILID,
    ACTIVESIGNATOR_EMAILID AS ACTIVESIGNATOR_EMAILID,
    ACTIVESIGNATOR_APPROVALSTATUS AS ACTIVESIGNATOR_APPROVALSTATUS,
    SELECTEDSIGNATORFORLOA_EMAILID AS SELECTEDSIGNATORFORLOA_EMAILID,
    SELECTEDSIGNATORFORLOA_APPROVALSTATUS AS SELECTEDSIGNATORFORLOA_APPROVALSTATUS,
    LOBLIMITS_LOBNAME AS LOBLIMITS_LOBNAME,
    LOBLIMITS_ACTION AS LOBLIMITS_ACTION,
    LOBLIMITS_ITEMLEVEL_TYPE AS LOBLIMITS_ITEMLEVEL_TYPE,
    LOBLIMITS_ITEMLEVEL_ITEMNAME AS LOBLIMITS_ITEMLEVEL_ITEMNAME,
    LOBLIMITS_ITEMLEVEL_LINEITEMS_NOLEVELS AS LOBLIMITS_ITEMLEVEL_LINEITEMS_NOLEVELS,
    LOBLIMITS_ITEMLEVEL_LINEITEMS_LEVELNAME AS LOBLIMITS_ITEMLEVEL_LINEITEMS_LEVELNAME,
    LOBLIMITS_ITEMLEVEL_LINEITEMS_CATEGORIES_FIELDNAME AS LOBLIMITS_ITEMLEVEL_LINEITEMS_CATEGORIES_FIELDNAME,
    LOBLIMITS_CONFIG_CATEGORIES_FIELDS_FIELDNAME AS LOBLIMITS_CONFIG_CATEGORIES_FIELDS_FIELDNAME,
    LOBLIMITS_CONFIG_CATEGORIES_FIELDS_COLUMNS_COLUMNNAME AS LOBLIMITS_CONFIG_CATEGORIES_FIELDS_COLUMNS_COLUMNNAME,
    LOBLIMITS_ITEMLEVEL_LINEITEMS_CATEGORIES_VALUES_VALUE AS LOBLIMITS_ITEMLEVEL_LINEITEMS_CATEGORIES_VALUES_VALUE,
    FILE_NAME AS FILE_NAME,
    FILE_DATE AS FILE_DATE,
    'AUTHORITIES_MYAUTHORITY_CLAIMS_DELTA' AS CTL_SRC_SYS_SET_NAME,
    (monotonically_increasing_id()) AS prophecy_sk,
    FILE_NAME AS Input
  
  FROM `30_MDL_AUTHORITIESmp_myauthorities_stg_mdl_dnm_AU_NZ_MyAuthority_Delta_SRC_AUTH_AU_NZ_MYAUTHORITY_ALLUSERS_DELTA` AS in0

),

EXP_AUTH_AUDIT_COLUMNS AS (

  SELECT 
    CURRENT_TIMESTAMP AS CTL_REC_INSERT_DATE,
    'Y' AS CTL_ACTIVE_STATUS,
    prophecy_sk AS prophecy_sk
  
  FROM EXP_INIT AS in0

),

DNM_AUTH_AU_NZ_MYAUTHORITY_ALLUSERS_DELTA_EXP_JOIN AS (

  SELECT 
    in1.ISBEHALFOFGRANTORSSIGNATORIES AS ISBEHALFOFGRANTORSSIGNATORIES,
    in1.ISREISSUED AS ISREISSUED,
    in1.ZURICHORG AS ZURICHORG,
    in1.LOBLIMITS_CONFIG_CATEGORIES_FIELDS_COLUMNS_COLUMNNAME AS LOBLIMITS_CONFIG_CATEGORIES_FIELDS_COLUMNS_COLUMNNAME,
    in1.LOBLIMITS_ACTION AS LOBLIMITS_ACTION,
    in1.FILE_NAME AS FILE_NAME,
    in1.CTL_SRC_SYS_SET_NAME AS CTL_SRC_SYS_SET_NAME,
    in1.USERROLE AS USERROLE,
    in1.USERNAME AS USERNAME,
    in1.ACTIVEGRANTOR_EMAILID AS ACTIVEGRANTOR_EMAILID,
    in1.LOBLIMITS_ITEMLEVEL_TYPE AS LOBLIMITS_ITEMLEVEL_TYPE,
    in1.EMAILID AS EMAILID,
    in1.STATUSLOG_UPDATEDDATE AS STATUSLOG_UPDATEDDATE,
    in1.LOBLIMITS_ITEMLEVEL_LINEITEMS_NOLEVELS AS LOBLIMITS_ITEMLEVEL_LINEITEMS_NOLEVELS,
    in1.INREISSUEDFLOW AS INREISSUEDFLOW,
    in1.LOBLIMITS_ITEMLEVEL_ITEMNAME AS LOBLIMITS_ITEMLEVEL_ITEMNAME,
    in1.USERID AS USERID,
    in1.SELECTEDGRANTORFORLOA_MAILID AS SELECTEDGRANTORFORLOA_MAILID,
    in1.LOATERMINATEDEFFECTIVEDATE AS LOATERMINATEDEFFECTIVEDATE,
    in1.HIDEUSD AS HIDEUSD,
    in0.CTL_REC_INSERT_DATE AS CTL_REC_INSERT_DATE,
    in1.SELECTEDSIGNATORFORLOA_APPROVALSTATUS AS SELECTEDSIGNATORFORLOA_APPROVALSTATUS,
    in1.DEPARTMENT AS DEPARTMENT,
    in1.ACTIVESIGNATOR_EMAILID AS ACTIVESIGNATOR_EMAILID,
    in1.USERTYPE AS USERTYPE,
    in1.FILE_DATE AS FILE_DATE,
    in1.COUNTRYNAME AS COUNTRYNAME,
    in1.LOBLIMITS_AUTOCONVERT AS LOBLIMITS_AUTOCONVERT,
    in1.LOBLIMITS_ITEMLEVEL_LINEITEMS_CATEGORIES_VALUES_VALUE AS LOBLIMITS_ITEMLEVEL_LINEITEMS_CATEGORIES_VALUES_VALUE,
    in1.MANAGER AS MANAGER,
    in1.STATUS AS STATUS,
    in0.prophecy_sk AS prophecy_sk,
    in1.MYAUTHORITYCOUNTRY AS MYAUTHORITYCOUNTRY,
    in1.ACTIVESIGNATOR_APPROVALSTATUS AS ACTIVESIGNATOR_APPROVALSTATUS,
    in1.INACTIVE AS INACTIVE,
    in1.REGIONNAME AS REGIONNAME,
    in1.LOBLIMITS_CONFIG_CATEGORIES_FIELDS_FIELDNAME AS LOBLIMITS_CONFIG_CATEGORIES_FIELDS_FIELDNAME,
    in1.OLDLOAEFFECTIVEDATE AS OLDLOAEFFECTIVEDATE,
    in1.LOAEFFECTIVEDATE AS LOAEFFECTIVEDATE,
    in1.TITLE AS TITLE,
    in1.LOBLIMITS_ITEMLEVEL_LINEITEMS_CATEGORIES_FIELDNAME AS LOBLIMITS_ITEMLEVEL_LINEITEMS_CATEGORIES_FIELDNAME,
    in1.LOBLIMITS_LOBNAME AS LOBLIMITS_LOBNAME,
    in1.LOBLIMITS_ITEMLEVEL_LINEITEMS_LEVELNAME AS LOBLIMITS_ITEMLEVEL_LINEITEMS_LEVELNAME,
    in1.ORGANIZATIONS AS ORGANIZATIONS,
    in1.SELECTEDSIGNATORFORLOA_EMAILID AS SELECTEDSIGNATORFORLOA_EMAILID,
    in0.CTL_ACTIVE_STATUS AS CTL_ACTIVE_STATUS,
    in1.ACTION AS ACTION,
    in1.Input AS Input,
    in1.ALLOWGRANTANDSIGNLOA AS ALLOWGRANTANDSIGNLOA,
    in1.ALLVALUESIN AS ALLVALUESIN
  
  FROM EXP_AUTH_AUDIT_COLUMNS AS in0
  INNER JOIN EXP_INIT AS in1
     ON (in0.prophecy_sk = in1.prophecy_sk)

),

DNM_AUTH_AU_NZ_MYAUTHORITY_ALLUSERS_DELTA_EXP AS (

  SELECT 
    USERID AS USERID,
    EMAILID AS EMAILID,
    USERNAME AS USERNAME,
    REGIONNAME AS REGIONNAME,
    COUNTRYNAME AS COUNTRYNAME,
    MYAUTHORITYCOUNTRY AS MYAUTHORITYCOUNTRY,
    ZURICHORG AS ZURICHORG,
    USERTYPE AS USERTYPE,
    USERROLE AS USERROLE,
    MANAGER AS MANAGER,
    DEPARTMENT AS DEPARTMENT,
    TITLE AS TITLE,
    ORGANIZATIONS AS ORGANIZATIONS,
    ALLOWGRANTANDSIGNLOA AS ALLOWGRANTANDSIGNLOA,
    STATUS AS STATUS,
    STATUSLOG_UPDATEDDATE AS STATUSLOG_UPDATEDDATE,
    LOAEFFECTIVEDATE AS LOAEFFECTIVEDATE,
    ACTION AS ACTION,
    INACTIVE AS INACTIVE,
    ISREISSUED AS ISREISSUED,
    INREISSUEDFLOW AS INREISSUEDFLOW,
    OLDLOAEFFECTIVEDATE AS OLDLOAEFFECTIVEDATE,
    LOATERMINATEDEFFECTIVEDATE AS LOATERMINATEDEFFECTIVEDATE,
    ALLVALUESIN AS ALLVALUESIN,
    LOBLIMITS_AUTOCONVERT AS LOBLIMITS_AUTOCONVERT,
    HIDEUSD AS HIDEUSD,
    ISBEHALFOFGRANTORSSIGNATORIES AS ISBEHALFOFGRANTORSSIGNATORIES,
    ACTIVEGRANTOR_EMAILID AS ACTIVEGRANTOR_EMAILID,
    SELECTEDGRANTORFORLOA_MAILID AS SELECTEDGRANTORFORLOA_MAILID,
    ACTIVESIGNATOR_EMAILID AS ACTIVESIGNATOR_EMAILID,
    ACTIVESIGNATOR_APPROVALSTATUS AS ACTIVESIGNATOR_APPROVALSTATUS,
    SELECTEDSIGNATORFORLOA_EMAILID AS SELECTEDSIGNATORFORLOA_EMAILID,
    SELECTEDSIGNATORFORLOA_APPROVALSTATUS AS SELECTEDSIGNATORFORLOA_APPROVALSTATUS,
    LOBLIMITS_LOBNAME AS LOBLIMITS_LOBNAME,
    LOBLIMITS_ACTION AS LOBLIMITS_ACTION,
    LOBLIMITS_ITEMLEVEL_TYPE AS LOBLIMITS_ITEMLEVEL_TYPE,
    LOBLIMITS_ITEMLEVEL_ITEMNAME AS LOBLIMITS_ITEMLEVEL_ITEMNAME,
    LOBLIMITS_ITEMLEVEL_LINEITEMS_NOLEVELS AS LOBLIMITS_ITEMLEVEL_LINEITEMS_NOLEVELS,
    LOBLIMITS_ITEMLEVEL_LINEITEMS_LEVELNAME AS LOBLIMITS_ITEMLEVEL_LINEITEMS_LEVELNAME,
    LOBLIMITS_ITEMLEVEL_LINEITEMS_CATEGORIES_FIELDNAME AS LOBLIMITS_ITEMLEVEL_LINEITEMS_CATEGORIES_FIELDNAME,
    LOBLIMITS_CONFIG_CATEGORIES_FIELDS_FIELDNAME AS LOBLIMITS_CONFIG_CATEGORIES_FIELDS_FIELDNAME,
    LOBLIMITS_CONFIG_CATEGORIES_FIELDS_COLUMNS_COLUMNNAME AS LOBLIMITS_CONFIG_CATEGORIES_FIELDS_COLUMNS_COLUMNNAME,
    LOBLIMITS_ITEMLEVEL_LINEITEMS_CATEGORIES_VALUES_VALUE AS LOBLIMITS_ITEMLEVEL_LINEITEMS_CATEGORIES_VALUES_VALUE,
    FILE_NAME AS FILE_NAME,
    FILE_DATE AS FILE_DATE,
    CTL_ACTIVE_STATUS AS CTL_ACTIVE_STATUS,
    CTL_SRC_SYS_SET_NAME AS CTL_SRC_SYS_SET_NAME,
    CTL_REC_INSERT_DATE AS CTL_REC_INSERT_DATE,
    CAST(NULL AS string) AS CTL_REC_UPDATE_DATE,
    prophecy_sk AS prophecy_sk
  
  FROM DNM_AUTH_AU_NZ_MYAUTHORITY_ALLUSERS_DELTA_EXP_JOIN AS in0

)

SELECT *

FROM DNM_AUTH_AU_NZ_MYAUTHORITY_ALLUSERS_DELTA_EXP
